function execute() {
    return Response.success([
        { title: "男-奇幻", input: "/books/nansheng?categoryId=1114", script: "zen.js" },
        { title: "男-玄幻", input: "/books/nansheng?categoryId=1115", script: "zen.js" },
        { title: "男-武侠", input: "/books/nansheng?categoryId=1116", script: "zen.js" },
        { title: "男-仙侠", input: "/books/nansheng?categoryId=1117", script: "zen.js" },
        { title: "男-都市", input: "/books/nansheng?categoryId=1118", script: "zen.js" },
        { title: "男-校园", input: "/books/nansheng?categoryId=1119", script: "zen.js" },
        { title: "男-历史", input: "/books/nansheng?categoryId=1120", script: "zen.js" },
        { title: "男-军事", input: "/books/nansheng?categoryId=1121", script: "zen.js" },
        { title: "男-游戏", input: "/books/nansheng?categoryId=1122", script: "zen.js" },
        { title: "男-竞技", input: "/books/nansheng?categoryId=1123", script: "zen.js" },
        { title: "男-科幻", input: "/books/nansheng?categoryId=1124", script: "zen.js" },
        { title: "男-灵异", input: "/books/nansheng?categoryId=1125", script: "zen.js" },
        { title: "Nam Tần", input: "namtan,", script: "tag.js" },
        { title: "Đô Thị", input: "dothi,", script: "tag.js" },
        { title: "Nhiệt Huyết", input: "nhiethuyet,", script: "tag.js" },
        { title: "Sát Phạt Quả Đoán", input: "satphatquadoan,", script: "tag.js" },
        { title: "Huyền Huyễn", input: "huyenhuyen,", script: "tag.js" },
        { title: "Nữ Tần", input: "nutan,", script: "tag.js" },
        { title: "Lịch Sử Vô Căn Cứ", input: "lichsuvocancu,", script: "tag.js" },
        { title: "Sảng Văn", input: "sangvan,", script: "tag.js" },
        { title: "Đô Thị Cao Thủ", input: "dothicaothu,", script: "tag.js" },
        { title: "Lịch Sử", input: "lichsu,", script: "tag.js" },
        { title: "Giả Heo Ăn Thịt Hổ", input: "giaheoanthitho,", script: "tag.js" },
        { title: "Đông Phương Huyền Huyễn", input: "dongphuonghuyenhuyen,", script: "tag.js" },
        { title: "Hộ Hoa Cao Thủ", input: "hohoacaothu,", script: "tag.js" },
        { title: "Nghịch Tập", input: "nghichtap,", script: "tag.js" },
        { title: "Cổ Đại Ngôn Tình", input: "codaingontinh,", script: "tag.js" },
        { title: "Võ Đạo", input: "vodao,", script: "tag.js" },
        { title: "Thăng Cấp Lưu", input: "thangcapluu,", script: "tag.js" },
        { title: "Cuộc Sống Đô Thị", input: "cuocsongdothi,", script: "tag.js" },
        { title: "Mưu Lược", input: "muuluoc,", script: "tag.js" },
        { title: "Xuyên Qua", input: "xuyenqua,", script: "tag.js" },
        { title: "Xấu Bụng", input: "xaubung,", script: "tag.js" },
        { title: "Luyện Công", input: "luyencong,", script: "tag.js" },
        { title: "Mạch Suy Nghĩ Thanh Kỳ", input: "machsuynghithanhky,", script: "tag.js" },
        { title: "Cường Giả Trở Về", input: "cuonggiatrove,", script: "tag.js" },
        { title: "Kiếm Tiền", input: "kiemtien,", script: "tag.js" },
        { title: "Bác Sĩ Lưu", input: "bacsiluu,", script: "tag.js" },
        { title: "Tình Yêu", input: "tinhyeu,", script: "tag.js" },
        { title: "Linh Dị", input: "linhdi,", script: "tag.js" },
        { title: "Dị Thế Đại Lục", input: "dithedailuc,", script: "tag.js" },
        { title: "Trùng Sinh", input: "trungsinh,", script: "tag.js" },
        { title: "Tiên Hiệp", input: "tienhiep,", script: "tag.js" },
        { title: "Tranh Bá", input: "tranhba,", script: "tag.js" },
        { title: "Huyền Nghi Lưu", input: "huyennghiluu,", script: "tag.js" },
        { title: "Hiện Đại Quỷ Bí", input: "hiendaiquybi,", script: "tag.js" },
        { title: "Trí Đấu", input: "tridau,", script: "tag.js" },
        { title: "Ngọt Sủng", input: "ngotsung,", script: "tag.js" },
        { title: "Dị Thuật Siêu Năng", input: "dithuatsieunang,", script: "tag.js" },
        { title: "Hiện Đại Ngôn Tình", input: "hiendaingontinh,", script: "tag.js" },
        { title: "Đánh Mặt", input: "danhmat,", script: "tag.js" },
        { title: "Xuyên Qua Thời Không", input: "xuyenquathoikhong,", script: "tag.js" },
        { title: "Hiện Đại Tu Chân", input: "hiendaituchan,", script: "tag.js" },
        { title: "Thường Ngày Văn", input: "thuongngayvan,", script: "tag.js" },
        { title: "Nữ Thần", input: "nuthan,", script: "tag.js" },
        { title: "Tiên Hiệp Cổ Điển", input: "tienhiepcodien,", script: "tag.js" },
        { title: "Báo Thù", input: "baothu,", script: "tag.js" },
        { title: "Thành Thục", input: "thanhthuc,", script: "tag.js" },
        { title: "Chí Tôn Lưu", input: "chitonluu,", script: "tag.js" },
        { title: "Nhẹ Nhõm", input: "nhenhom,", script: "tag.js" },
        { title: "Thám Hiểm", input: "thamhiem,", script: "tag.js" },
        { title: "Trò Chơi", input: "trochoi,", script: "tag.js" },
        { title: "Thiên Tài Lưu", input: "thientailuu,", script: "tag.js" },
        { title: "Vô Địch Lưu", input: "vodichluu,", script: "tag.js" },
        { title: "Trí Thông Minh Tại Tuyến", input: "trithongminhtaituyen,", script: "tag.js" },
        { title: "Tổng Giám Đốc Hào Môn", input: "tonggiamdochaomon,", script: "tag.js" },
        { title: "Quyền Mưu", input: "quyenmuu,", script: "tag.js" },
        { title: "Người Ở Rể Lưu", input: "nguoioreluu,", script: "tag.js" },
        { title: "Khoa Huyễn", input: "khoahuyen,", script: "tag.js" },
        { title: "Sợi Cỏ Quật Khởi", input: "soicoquatkhoi,", script: "tag.js" },
        { title: "Binh Vương", input: "binhvuong,", script: "tag.js" },
        { title: "Loạn Thế", input: "loanthe,", script: "tag.js" },
        { title: "Triều Đình Giang Hồ", input: "trieudinhgiangho,", script: "tag.js" },
        { title: "Y Đạo Thánh Thủ", input: "ydaothanhthu,", script: "tag.js" },
        { title: "Hệ Thống Lưu", input: "hethongluu,", script: "tag.js" },
        { title: "Tổng Giám Đốc", input: "tonggiamdoc,", script: "tag.js" },
        { title: "Tỉnh Táo", input: "tinhtao,", script: "tag.js" },
        { title: "Kinh Dị Kinh Khủng", input: "kinhdikinhkhung,", script: "tag.js" },
        { title: "Cổ Kính", input: "cokinh,", script: "tag.js" },
        { title: "Não Động Lớn", input: "naodonglon,", script: "tag.js" },
        { title: "Dị Năng", input: "dinang,", script: "tag.js" },
        { title: "Triều Đình", input: "trieudinh,", script: "tag.js" },
        { title: "Làm Ruộng", input: "lamruong,", script: "tag.js" },
        { title: "Cường Giả Lưu", input: "cuonggialuu,", script: "tag.js" },
        { title: "Bắt Đầu Lưu", input: "batdauluu,", script: "tag.js" },
        { title: "Du Hí Dị Giới", input: "duhidigioi,", script: "tag.js" },
        { title: "Lưỡng Tống Nguyên Minh", input: "luongtongnguyenminh,", script: "tag.js" },
        { title: "Luyện Đan", input: "luyendan,", script: "tag.js" },
        { title: "Lâu Ngày Sinh Tình", input: "laungaysinhtinh,", script: "tag.js" },
        { title: "Đảo Ngược", input: "daonguoc,", script: "tag.js" },
        { title: "Thế Giới Tương Lai", input: "thegioituonglai,", script: "tag.js" },
        { title: "Nhanh Tiết Tấu", input: "nhanhtiettau,", script: "tag.js" },
        { title: "Đô Thị Tu Tiên", input: "dothitutien,", script: "tag.js" },
        { title: "Nữ Cường", input: "nucuong,", script: "tag.js" },
        { title: "Minh Triều", input: "minhtrieu,", script: "tag.js" },
        { title: "Võng Du", input: "vongdu,", script: "tag.js" },
        { title: "Hào Môn", input: "haomon,", script: "tag.js" },
        { title: "Thương Nghiệp Ông Trùm", input: "thuongnghiepongtrum,", script: "tag.js" },
        { title: "Dị Thế Xuyên Qua", input: "dithexuyenqua,", script: "tag.js" },
        { title: "Gia Tộc", input: "giatoc,", script: "tag.js" },
        { title: "Thám Tử Suy Luận", input: "thamtusuyluan,", script: "tag.js" },
        { title: "Phấn Đấu", input: "phandau,", script: "tag.js" },
        { title: "Kinh Doanh", input: "kinhdoanh,", script: "tag.js" },
        { title: "Chiến Thần Lưu", input: "chienthanluu,", script: "tag.js" },
        { title: "Tận Thế Nguy Cơ", input: "tanthenguyco,", script: "tag.js" },
        { title: "Tự Cường", input: "tucuong,", script: "tag.js" },
        { title: "Tận Thế", input: "tanthe,", script: "tag.js" },
        { title: "Nữ Tổng Giám Đốc", input: "nutonggiamdoc,", script: "tag.js" },
        { title: "Cẩn Thận", input: "canthan,", script: "tag.js" },
        { title: "Huyền Học", input: "huyenhoc,", script: "tag.js" },
        { title: "Tự Hạn Chế", input: "tuhanche,", script: "tag.js" },
        { title: "Cao Thủ Xuống Núi", input: "caothuxuongnui,", script: "tag.js" },
        { title: "Kỳ Huyễn Tu Chân", input: "kyhuyentuchan,", script: "tag.js" },
        { title: "Niên Đại Văn", input: "niendaivan,", script: "tag.js" },
        { title: "Bá Đạo", input: "badao,", script: "tag.js" },
        { title: "Cướp Quyền", input: "cuopquyen,", script: "tag.js" },
        { title: "Củi Mục Lưu", input: "cuimucluu,", script: "tag.js" },
        { title: "Kỳ Huyễn", input: "kyhuyen,", script: "tag.js" },
        { title: "Nông Thôn", input: "nongthon,", script: "tag.js" },
        { title: "Cung Đấu Trạch Đấu", input: "cungdautrachdau,", script: "tag.js" },
        { title: "Tình Yêu Và Hôn Nhân", input: "tinhyeuvahonnhan,", script: "tag.js" },
        { title: "Hư Nghĩ Võng Du", input: "hunghivongdu,", script: "tag.js" },
        { title: "Cùng Người Tác Phẩm", input: "cungnguoitacpham,", script: "tag.js" },
        { title: "Võ Hiệp", input: "vohiep,", script: "tag.js" },
        { title: "Đích Nữ", input: "dichnu,", script: "tag.js" },
        { title: "Sinh Tồn Khiêu Chiến", input: "sinhtonkhieuchien,", script: "tag.js" },
        { title: "Truy Thê", input: "truythe,", script: "tag.js" },
        { title: "Chiến Tranh", input: "chientranh,", script: "tag.js" },
        { title: "Trường Sinh", input: "truongsinh,", script: "tag.js" },
        { title: "Sủng Thê", input: "sungthe,", script: "tag.js" },
        { title: "Tần Hán Tam Quốc", input: "tanhantamquoc,", script: "tag.js" },
        { title: "Nhiều Nữ Chính", input: "nhieunuchinh,", script: "tag.js" },
        { title: "Nông Môn", input: "nongmon,", script: "tag.js" },
        { title: "Thần Y", input: "thany,", script: "tag.js" },
        { title: "Hồng Hoang", input: "honghoang,", script: "tag.js" },
        { title: "Bật Hack Lưu", input: "bathackluu,", script: "tag.js" },
        { title: "Khôi Hài", input: "khoihai,", script: "tag.js" },
        { title: "Tiến Hóa", input: "tienhoa,", script: "tag.js" },
        { title: "Hoàng Tử", input: "hoangtu,", script: "tag.js" },
        { title: "Lưỡng Tấn Tùy Đường", input: "luongtantuyduong,", script: "tag.js" },
        { title: "Thần Thoại", input: "thanthoai,", script: "tag.js" },
        { title: "Vui Chơi Giải Trí", input: "vuichoigiaitri,", script: "tag.js" },
        { title: "Phong Thần", input: "phongthan,", script: "tag.js" },
        { title: "Tam Quốc", input: "tamquoc,", script: "tag.js" },
        { title: "Học Sinh", input: "hocsinh,", script: "tag.js" },
        { title: "Đường Triều", input: "duongtrieu,", script: "tag.js" },
        { title: "Thương Chiến", input: "thuongchien,", script: "tag.js" },
        { title: "Tây Phương Kỳ Huyễn", input: "tayphuongkyhuyen,", script: "tag.js" },
        { title: "Lập Nghiệp", input: "lapnghiep,", script: "tag.js" },
        { title: "Khoa Học Kỹ Thuật", input: "khoahockythuat,", script: "tag.js" },
        { title: "Giải Trí Minh Tinh", input: "giaitriminhtinh,", script: "tag.js" },
        { title: "Hương Thổ Sinh Hoạt", input: "huongthosinhhoat,", script: "tag.js" },
        { title: "Huyễn Tưởng Ngôn Tình", input: "huyentuongngontinh,", script: "tag.js" },
        { title: "Truyền Thống Võ Hiệp", input: "truyenthongvohiep,", script: "tag.js" },
        { title: "Thế Gia", input: "thegia,", script: "tag.js" },
        { title: "Suy Luận Huyền Nghi", input: "suyluanhuyennghi,", script: "tag.js" },
        { title: "Cung Đấu", input: "cungdau,", script: "tag.js" },
        { title: "Ma Pháp", input: "maphap,", script: "tag.js" },
        { title: "Trò Chơi Người Chơi", input: "trochoinguoichoi,", script: "tag.js" },
        { title: "Yêu Nhau", input: "yeunhau,", script: "tag.js" },
        { title: "Giám Bảo", input: "giambao,", script: "tag.js" },
        { title: "Minh Tinh", input: "minhtinh,", script: "tag.js" },
        { title: "Trạch Đấu", input: "trachdau,", script: "tag.js" },
        { title: "Tiên Đế", input: "tiende,", script: "tag.js" },
        { title: "Dị Thú Lưu", input: "dithuluu,", script: "tag.js" },
        { title: "Đạo Sĩ", input: "daosi,", script: "tag.js" },
        { title: "Hoan Hỉ Oan Gia", input: "hoanhioangia,", script: "tag.js" },
        { title: "Thái Giám", input: "thaigiam,", script: "tag.js" },
        { title: "Hồng Hoang Phong Thần", input: "honghoangphongthan,", script: "tag.js" },
        { title: "Lão Bản", input: "laoban,", script: "tag.js" },
        { title: "Tinh Tế", input: "tinhte,", script: "tag.js" },
        { title: "Hoa Ngu", input: "hoangu,", script: "tag.js" },
        { title: "Thi Đấu", input: "thidau,", script: "tag.js" },
        { title: "Quân Sự", input: "quansu,", script: "tag.js" },
        { title: "Thịnh Thế", input: "thinhthe,", script: "tag.js" },
        { title: "Sân Trường", input: "santruong,", script: "tag.js" },
        { title: "Phong Thuỷ Huyền Thuật", input: "phongthuyhuyenthuat,", script: "tag.js" },
        { title: "Đánh Dấu", input: "danhdau,", script: "tag.js" },
        { title: "Linh Khí Khôi Phục", input: "linhkhikhoiphuc,", script: "tag.js" },
        { title: "Chỗ Làm Việc", input: "cholamviec,", script: "tag.js" },
        { title: "Tam Quan Đang", input: "tamquandang,", script: "tag.js" },
        { title: "Ngọt Ngược", input: "ngotnguoc,", script: "tag.js" },
        { title: "Ngược Cặn Bã", input: "nguoccanba,", script: "tag.js" },
        { title: "Tông Môn", input: "tongmon,", script: "tag.js" },
        { title: "Đoàn Sủng", input: "doansung,", script: "tag.js" },
        { title: "Thiểm Hôn", input: "thiemhon,", script: "tag.js" },
        { title: "Độc Sủng", input: "docsung,", script: "tag.js" },
        { title: "Kỹ Thuật Lưu", input: "kythuatluu,", script: "tag.js" },
        { title: "Tần Hán", input: "tanhan,", script: "tag.js" },
        { title: "Trước Tiên Cưới Sau Thích", input: "truoctiencuoisauthich,", script: "tag.js" },
        { title: "Đơn Nữ Chính", input: "donnuchinh,", script: "tag.js" },
        { title: "Điện Cạnh", input: "diencanh,", script: "tag.js" },
        { title: "Kiêu Hùng", input: "kieuhung,", script: "tag.js" },
        { title: "Tiên Hiệp Huyễn Tình", input: "tienhiephuyentinh,", script: "tag.js" },
        { title: "Áo Lót", input: "aolot,", script: "tag.js" },
        { title: "Tây Du", input: "taydu,", script: "tag.js" },
        { title: "Kiếm Cùng Ma Pháp", input: "kiemcungmaphap,", script: "tag.js" },
        { title: "Manh Bảo", input: "manhbao,", script: "tag.js" },
        { title: "Đại Lão", input: "dailao,", script: "tag.js" },
        { title: "Linh Căn", input: "linhcan,", script: "tag.js" },
        { title: "Luyện Công Lưu", input: "luyencongluu,", script: "tag.js" },
        { title: "Nông Dân", input: "nongdan,", script: "tag.js" },
        { title: "Sắp Đặt Lưu", input: "sapdatluu,", script: "tag.js" },
        { title: "Gương Vỡ Lại Lành", input: "guongvolailanh,", script: "tag.js" },
        { title: "Làm Giàu", input: "lamgiau,", script: "tag.js" },
        { title: "Triệu Hoán Lưu", input: "trieuhoanluu,", script: "tag.js" },
        { title: "Phía Sau Màn Lưu", input: "phiasaumanluu,", script: "tag.js" },
        { title: "Mỹ Thực", input: "mythuc,", script: "tag.js" },
        { title: "Xuyên Thư", input: "xuyenthu,", script: "tag.js" },
        { title: "Chư Thiên Lưu", input: "chuthienluu,", script: "tag.js" },
        { title: "Ly Hôn", input: "lyhon,", script: "tag.js" },
        { title: "Vương Phi", input: "vuongphi,", script: "tag.js" },
        { title: "Thiên Kim", input: "thienkim,", script: "tag.js" },
        { title: "Thực Tế Ảo", input: "thucteao,", script: "tag.js" },
        { title: "Cường Cường", input: "cuongcuong,", script: "tag.js" },
        { title: "Ánh Trăng Sáng", input: "anhtrangsang,", script: "tag.js" },
        { title: "Phàm Nhân Lưu", input: "phamnhanluu,", script: "tag.js" },
        { title: "Đồ Cổ Giám Bảo", input: "docogiambao,", script: "tag.js" },
        { title: "Trò Chơi Kiếp Sống", input: "trochoikiepsong,", script: "tag.js" },
        { title: "Sát Thủ", input: "satthu,", script: "tag.js" },
        { title: "Ấm Áp", input: "amap,", script: "tag.js" },
        { title: "Người Chơi", input: "nguoichoi,", script: "tag.js" },
        { title: "Nữ Tôn Nữ Cường", input: "nutonnucuong,", script: "tag.js" },
        { title: "Kiếm Tu", input: "kiemtu,", script: "tag.js" },
        { title: "Chiến Tranh Kháng Nhật", input: "chientranhkhangnhat,", script: "tag.js" },
        { title: "Dưỡng Thành", input: "duongthanh,", script: "tag.js" },
        { title: "Luyện Khí", input: "luyenkhi,", script: "tag.js" },
        { title: "Vô Hạn Lưu", input: "vohanluu,", script: "tag.js" },
        { title: "Quân Lữ", input: "quanlu,", script: "tag.js" },
        { title: "Vú Em", input: "vuem,", script: "tag.js" },
        { title: "Tương Ái Tương Sát", input: "tuongaituongsat,", script: "tag.js" },
        { title: "Làm Ruộng Kinh Thương", input: "lamruongkinhthuong,", script: "tag.js" },
        { title: "Nữ Phối", input: "nuphoi,", script: "tag.js" },
        { title: "Cá Chép", input: "cachep,", script: "tag.js" },
        { title: "Nghề Nghiệp Văn", input: "nghenghiepvan,", script: "tag.js" },
        { title: "Thể Dục Thi Đấu", input: "theducthidau,", script: "tag.js" },
        { title: "Tống Triều", input: "tongtrieu,", script: "tag.js" },
        { title: "Trước Tiên Cưới Sau Yêu", input: "truoctiencuoisauyeu,", script: "tag.js" },
        { title: "Dong Binh", input: "dongbinh,", script: "tag.js" },
        { title: "Phi Thăng", input: "phithang,", script: "tag.js" },
        { title: "Tương Lai Võng Du", input: "tuonglaivongdu,", script: "tag.js" },
        { title: "Vương Giả Vinh Quang", input: "vuonggiavinhquang,", script: "tag.js" },
        { title: "Hoang Dã Cầu Sinh", input: "hoangdacausinh,", script: "tag.js" },
        { title: "Kiếp Trước Và Kiếp Này", input: "kieptruocvakiepnay,", script: "tag.js" },
        { title: "Tháo Hán", input: "thaohan,", script: "tag.js" },
        { title: "Dị Năng Giả", input: "dinanggia,", script: "tag.js" },
        { title: "Làm Quái", input: "lamquai,", script: "tag.js" },
        { title: "Tướng Quân", input: "tuongquan,", script: "tag.js" },
        { title: "Cảnh Sát", input: "canhsat,", script: "tag.js" },
        { title: "Hoàng Đế Lưu", input: "hoangdeluu,", script: "tag.js" },
        { title: "Tiến Hóa Biến Dị", input: "tienhoabiendi,", script: "tag.js" },
        { title: "Ngành Giải Trí", input: "nganhgiaitri,", script: "tag.js" },
        { title: "Thanh Mai Trúc Mã", input: "thanhmaitrucma,", script: "tag.js" },
        { title: "Hoàn Khố", input: "hoankho,", script: "tag.js" },
        { title: "Thượng Cổ Tiên Tần", input: "thuongcotientan,", script: "tag.js" },
        { title: "Cẩm Y Vệ", input: "camyve,", script: "tag.js" },
        { title: "Rút Thưởng", input: "rutthuong,", script: "tag.js" },
        { title: "Thiện Lương", input: "thienluong,", script: "tag.js" },
        { title: "Kinh Dị Kinh Khủng", input: "kinhdikinhkhung,", script: "tag.js" },
        { title: "Hình Sự Trinh Sát", input: "hinhsutrinhsat,", script: "tag.js" },
        { title: "Thiết Huyết", input: "thiethuyet,", script: "tag.js" },
        { title: "Lão Sư", input: "laosu,", script: "tag.js" },
        { title: "Bảo Tiêu", input: "baotieu,", script: "tag.js" },
        { title: "Ngạo Kiều", input: "ngaokieu,", script: "tag.js" },
        { title: "Vương Hầu", input: "vuonghau,", script: "tag.js" },
        { title: "Tùy Đường", input: "tuyduong,", script: "tag.js" },
        { title: "Ngự Thú Lưu", input: "nguthuluu,", script: "tag.js" },
        { title: "Sủng Vật", input: "sungvat,", script: "tag.js" },
        { title: "Sách Lược Lưu", input: "sachluocluu,", script: "tag.js" },
        { title: "Quyền Thần", input: "quyenthan,", script: "tag.js" },
        { title: "Bảo An", input: "baoan,", script: "tag.js" },
        { title: "Ngược Văn", input: "nguocvan,", script: "tag.js" },
        { title: "Học Bá", input: "hocba,", script: "tag.js" },
        { title: "Cực Phẩm", input: "cucpham,", script: "tag.js" },
        { title: "Nhanh Xuyên", input: "nhanhxuyen,", script: "tag.js" },
        { title: "Phản Sáo Lộ", input: "phansaolo,", script: "tag.js" },
        { title: "Muộn Tao", input: "muontao,", script: "tag.js" },
        { title: "Trạch Nam", input: "trachnam,", script: "tag.js" },
        { title: "Thanh Sử Dân Quốc", input: "thanhsudanquoc,", script: "tag.js" },
        { title: "Nhân Vật Phản Diện", input: "nhanvatphandien,", script: "tag.js" },
        { title: "Không Gian", input: "khonggian,", script: "tag.js" },
        { title: "Tu Tiên", input: "tutien,", script: "tag.js" },
        { title: "Thật Giả Thiên Kim", input: "thatgiathienkim,", script: "tag.js" },
        { title: "Tu Chân", input: "tuchan,", script: "tag.js" },
        { title: "Lính Đặc Chủng", input: "linhdacchung,", script: "tag.js" },
        { title: "Đấu Khí Thế Giới", input: "daukhithegioi,", script: "tag.js" },
        { title: "Thành Thần Lưu", input: "thanhthanluu,", script: "tag.js" },
        { title: "Nhiệt Huyết Sân Trường", input: "nhiethuyetsantruong,", script: "tag.js" },
        { title: "Viễn Cổ Thần Thoại", input: "viencothanthoai,", script: "tag.js" },
        { title: "Ngả Bài Lưu", input: "ngabailuu,", script: "tag.js" },
        { title: "Độc Phi", input: "docphi,", script: "tag.js" },
        { title: "Thái Tử Phi", input: "thaituphi,", script: "tag.js" },
        { title: "Giá Không", input: "giakhong,", script: "tag.js" },
        { title: "Siêu Cấp Khoa Học Kỹ Thuật", input: "sieucapkhoahockythuat,", script: "tag.js" },
        { title: "Không Kim Thủ Chỉ", input: "khongkimthuchi,", script: "tag.js" },
        { title: "Chiến Tranh Giữa Các Hành Tinh", input: "chientranhgiuacachanhtinh,", script: "tag.js" },
        { title: "Chat Group", input: "chatgroup,", script: "tag.js" },
        { title: "Huyền Nghi Suy Luận", input: "huyennghisuyluan,", script: "tag.js" },
        { title: "Manh Hệ", input: "manhhe,", script: "tag.js" },
        { title: "Hoàng Thúc", input: "hoangthuc,", script: "tag.js" },
        { title: "Sân Trường Sinh Hoạt", input: "santruongsinhhoat,", script: "tag.js" },
        { title: "Mang Bên Mình Lưu", input: "mangbenminhluu,", script: "tag.js" },
        { title: "Thiên Tài", input: "thientai,", script: "tag.js" },
        { title: "Lộ Ra Ánh Sáng Lưu", input: "loraanhsangluu,", script: "tag.js" },
        { title: "Thời Không Văn", input: "thoikhongvan,", script: "tag.js" },
        { title: "Chiến Sĩ", input: "chiensi,", script: "tag.js" },
        { title: "Thiên Đình Văn", input: "thiendinhvan,", script: "tag.js" },
        { title: "Đại Gả", input: "daiga,", script: "tag.js" },
        { title: "Đi Làm", input: "dilam,", script: "tag.js" },
        { title: "Chữa Trị", input: "chuatri,", script: "tag.js" },
        { title: "Đặc Công", input: "daccong,", script: "tag.js" },
        { title: "Vương Gia", input: "vuonggia,", script: "tag.js" },
        { title: "Đối Thủ Một Mất Một Còn", input: "doithumotmatmotcon,", script: "tag.js" },
        { title: "Bao Che Khuyết Điểm", input: "baochekhuyetdiem,", script: "tag.js" },
        { title: "Hắc Hóa", input: "hachoa,", script: "tag.js" },
        { title: "Vương Triều Tranh Bá", input: "vuongtrieutranhba,", script: "tag.js" },
        { title: "Khoa Cử", input: "khoacu,", script: "tag.js" },
        { title: "Miệng Pháo", input: "miengphao,", script: "tag.js" },
        { title: "Nhà Giàu Nhất", input: "nhagiaunhat,", script: "tag.js" },
        { title: "Tài Chính", input: "taichinh,", script: "tag.js" },
        { title: "Bệnh Kiều", input: "benhkieu,", script: "tag.js" },
        { title: "Trung Y Lưu", input: "trungyluu,", script: "tag.js" },
        { title: "Đạo Tặc", input: "daotac,", script: "tag.js" },
        { title: "Cường Quốc", input: "cuongquoc,", script: "tag.js" },
        { title: "Pháp Sư", input: "phapsu,", script: "tag.js" },
        { title: "Trinh Quán", input: "trinhquan,", script: "tag.js" },
        { title: "Kỳ Huyễn Lịch Sử", input: "kyhuyenlichsu,", script: "tag.js" },
        { title: "Đại Sư Huynh", input: "daisuhuynh,", script: "tag.js" },
        { title: "Tiểu Binh", input: "tieubinh,", script: "tag.js" },
        { title: "Bạch Liên Hoa", input: "bachlienhoa,", script: "tag.js" },
        { title: "Thuần Ái", input: "thuanai,", script: "tag.js" },
        { title: "Làm Dân Giàu", input: "lamdangiau,", script: "tag.js" },
        { title: "Hiện Đại Võ Hiệp", input: "hiendaivohiep,", script: "tag.js" },
        { title: "Thuật Sĩ", input: "thuatsi,", script: "tag.js" },
        { title: "Ma Pháp Sân Trường", input: "maphapsantruong,", script: "tag.js" },
        { title: "Đoạt Xá", input: "doatxa,", script: "tag.js" },
        { title: "Thợ Săn", input: "thosan,", script: "tag.js" },
        { title: "Điềm Thê", input: "diemthe,", script: "tag.js" },
        { title: "Cao Lãnh", input: "caolanh,", script: "tag.js" },
        { title: "Hàn Môn Tử Đệ", input: "hanmontude,", script: "tag.js" },
        { title: "Vua Màn Ảnh", input: "vuamananh,", script: "tag.js" },
        { title: "Thăng Cấp", input: "thangcap,", script: "tag.js" },
        { title: "Yêu Tinh Tình Duyên", input: "yeutinhtinhduyen,", script: "tag.js" },
        { title: "Ngu Dại", input: "ngudai,", script: "tag.js" },
        { title: "Vị Diện", input: "vidien,", script: "tag.js" },
        { title: "Bác Sĩ", input: "bacsi,", script: "tag.js" },
        { title: "Thuộc Tính Lưu", input: "thuoctinhluu,", script: "tag.js" },
        { title: "Kháng Chiến", input: "khangchien,", script: "tag.js" },
        { title: "Khoa Học Kỹ Thuật Tu Chân", input: "khoahockythuattuchan,", script: "tag.js" },
        { title: "Nam Thần", input: "namthan,", script: "tag.js" },
        { title: "Nhà Thiết Kế", input: "nhathietke,", script: "tag.js" },
        { title: "Ra Mắt", input: "ramat,", script: "tag.js" },
        { title: "Phò Mã", input: "phoma,", script: "tag.js" },
        { title: "Không Nữ Chính", input: "khongnuchinh,", script: "tag.js" },
        { title: "Hí Kịch Tinh", input: "hikichtinh,", script: "tag.js" },
        { title: "Nữ Chính Manh Em Bé", input: "nuchinhmanhembe,", script: "tag.js" },
        { title: "Tổng Mạn", input: "tongman,", script: "tag.js"
        }
    ]);
}
