let voices = [
  { "id": "Ngọc Huyền (mới)", "language": "vi" },
  { "id": "Mai Phương", "language": "vi" },
  { "id": "Duy Onyx (mới)", "language": "vi" },
  { "id": "Ngọc Ngạn", "language": "vi" },
  { "id": "Ban Mai", "language": "vi" },
  { "id": "Chiếu Thành", "language": "vi" },
  { "id": "Duy Oryx", "language": "vi" },
  { "id": "Lạc Phi", "language": "vi" },
  { "id": "Minh Khang", "language": "vi" },
  { "id": "Minh Quang", "language": "vi" },
  { "id": "Mạnh Dũng", "language": "vi" },
  { "id": "Mỹ Tâm", "language": "vi" },
  { "id": "Mỹ Tâm Real", "language": "vi" },
  { "id": "Phương Trang", "language": "vi" },
  { "id": "Thanh Phương Viettel", "language": "vi" },
  { "id": "Thiện Tâm", "language": "vi" },
  { "id": "Trấn Thành", "language": "vi" },
  { "id": "Tài An", "language": "vi" },
  { "id": "Việt Thảo", "language": "vi" },
  { "id": "adam", "language": "vi" }
];
