function execute() {
    return Response.success([
        {"title": "Update", "input": "/shuku/0_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "View", "input": "/shuku/allvisit_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "New", "input": "/shuku/postdate_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "View month", "input": "/shuku/monthvisit_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "View week", "input": "/shuku/weekvisit_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "View day", "input": "/shuku/dayvisit_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "Vote", "input": "/shuku/allvote_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "Vote month", "input": "/shuku/monthvote_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "Vote week", "input": "/shuku/weekvote_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "Vote day", "input": "/shuku/dayvote_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "Rate", "input": "/shuku/goodnum_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "字数", "input": "/shuku/size_0_0_{0}.html", "script": "gen_male.js"},
        {"title": "玄幻", "input": "/shuku/0_1_0_{0}.html", "script": "gen.js"},
        {"title": "奇幻", "input": "/shuku/0_2_0_{0}.html", "script": "gen.js"},
        {"title": "武侠", "input": "/shuku/0_3_0_{0}.html", "script": "gen.js"},
        {"title": "仙侠", "input": "/shuku/0_14_0_{0}.html", "script": "gen.js"},
        {"title": "都市", "input": "/shuku/0_4_0_{0}.html", "script": "gen.js"},
        {"title": "历史", "input": "/shuku/0_5_0_{0}.html", "script": "gen.js"},
        {"title": "军事", "input": "/shuku/0_6_0_{0}.html", "script": "gen.js"},
        {"title": "悬疑", "input": "/shuku/0_7_0_{0}.html", "script": "gen.js"},
        {"title": "游戏", "input": "/shuku/0_8_0_{0}.html", "script": "gen.js"},
        {"title": "科幻", "input": "/shuku/0_9_0_{0}.html", "script": "gen.js"},
        {"title": "体育", "input": "/shuku/0_10_0_{0}.html", "script": "gen.js"},
        {"title": "古言", "input": "/shuku/0_11_0_{0}.html", "script": "gen.js"},
        {"title": "现言", "input": "/shuku/0_12_0_{0}.html", "script": "gen.js"},
        {"title": "幻言", "input": "/shuku/0_13_0_{0}.html", "script": "gen.js"},
        {"title": "青春", "input": "/shuku/0_15_0_{0}.html", "script": "gen.js"},
        {"title": "穿越", "input": "/shuku/0_16_0_{0}.html", "script": "gen.js"},
        {"title": "女生", "input": "/shuku/0_17_0_{0}.html", "script": "gen.js"},
        {"title": "其他", "input": "/shuku/0_18_0_{0}.html", "script": "gen.js"}
    ]);
}