load("config.js");

function execute() {
	return Response.success([
		{ title: "诸天", input: "诸天", script: "search.js" },
        { title: "聊天群", input: "聊天群", script: "search.js" },
        { title: "万界", input: "万界", script: "search.js" },
        { title: "无限", input: "无限", script: "search.js" },
        { title: "同时穿越", input: "同时穿越", script: "search.js" }, //Đồng thời xuyên qua
        { title: "轮回", input: "轮回", script: "search.js" }, //Luân Hồi
        { title: "御兽", input: "御兽", script: "search.js" }, //Ngự thú

        //Tu chân liêu thiên quần
        { title: "修真聊天群", input: "修真聊天群", script: "search.js" },
        { title: "霸宋", input: "霸宋", script: "search.js" },
        { title: "宋书航", input: "宋书航", script: "search.js" },

        //Ngã cật tây hồng thị
        { title: "盘龙", input: "盘龙", script: "search.js" }, //Bàn Long
        { title: "吞噬", input: "吞噬", script: "search.js" }, //Thôn Phệ
        { title: "星辰变", input: "星辰变", script: "search.js" }, //Tinh thần biến
        { title: "沧元图", input: "沧元图", script: "search.js" }, //Thương nguyên đồ

        //Trạch Trư
        { title: "牧神记", input: "牧神记", script: "search.js" }, //Mục thần ký
        { title: "帝尊", input: "帝尊", script: "search.js" }, //Đế Tôn
        { title: "魔狱玄胎", input: "魔狱玄胎", script: "search.js" }, //Ma ngục huyền thai

        //Thần Đông
        { title: "神墓", input: "神墓", script: "search.js" }, //Thần Mộ
        { title: "遮天", input: "遮天", script: "search.js" }, //Già Thiên
        { title: "完美世界", input: "完美世界", script: "search.js" }, //Hoàn Mỹ Thế Giới
        { title: "圣墟", input: "圣墟", script: "search.js" }, //Thánh Khư

        //Vong ngữ
        { title: "凡人", input: "凡人", script: "search.js" }, //Phàm Nhân

        //Nhĩ căn
        { title: "仙逆", input: "仙逆", script: "search.js" }, //Tiên nghịch

        //Lão mực
        { title: "一世之尊", input: "一世之尊", script: "search.js" }, //Nhất thế chi tôn
        { title: "孟奇", input: "孟奇", script: "search.js" }, //Mạnh Kỳ
        { title: "诡秘", input: "诡秘", script: "search.js" }, //Quỷ bí

        //Mộng nhập
        { title: "永生", input: "永生", script: "search.js" }, //Vĩnh sinh
        { title: "阳神", input: "阳神", script: "search.js" }, //Dương Thần

        { title: "西游", input: "西游", script: "search.js" }, //Tây du
        { title: "洪荒", input: "洪荒", script: "search.js" }, //Hồng hoang
        { title: "大奉", input: "大奉", script: "search.js" }, //Đại Phụng
        { title: "庆余年", input: "庆余年", script: "search.js" }, //Khánh dư niên

        //Tam thiếu
        { title: "斗罗", input: "斗罗", script: "search.js" }, //Đấu la
        { title: "武魂", input: "武魂", script: "search.js" }, //Võ hồn
        { title: "神印", input: "神印", script: "search.js" }, //Thần ấn

        //Đấu phá
        { title: "斗破", input: "斗破", script: "search.js" }, //Đấu phá
        { title: "武动", input: "武动", script: "search.js" }, //Vũ động
        { title: "大主宰", input: "大主宰", script: "search.js" }, //Đại chúa tể
        { title: "元尊", input: "元尊", script: "search.js" }, //Nguyên tôn

        { title: "妖神记", input: "妖神记", script: "search.js" }, //Yêu thần ký
        { title: "师兄啊", input: "师兄啊", script: "search.js" }, //Sư huynh a
        { title: "全職法師", input: "全職法師", script: "search.js" }, //Toàn Chức Pháp Sư
        { title: "剑来", input: "剑来", script: "search.js" }, //Kiếm lai
        { title: "雪中", input: "雪中", script: "search.js" }, //Tuyết trung

        { title: "全球高武", input: "全球高武", script: "search.js" }, //Toàn Cầu Cao Võ
        { title: "万族之劫", input: "万族之劫", script: "search.js" }, //Vạn Tộc Chi Kiếp
        { title: "星门", input: "星门", script: "search.js" }, //Tinh Môn

        { title: "剑道独尊", input: "剑道独尊", script: "search.js" }, //Kiếm đạo độc tôn

        { title: "哈利波特", input: "哈利波特", script: "search.js" }, //Harry Potter
        { title: "霍格沃兹", input: "霍格沃兹", script: "search.js" }, //Hogwart

        //Comic
        { title: "美漫", input: "美漫", script: "search.js" }, //Comic
        { title: "漫威", input: "漫威", script: "search.js" }, //Marvel

        //Trung mạn
        { title: "磁场转动", input: "磁场转动", script: "search.js" }, //Từ Trường Chuyển Động

        { title: "绝世武神", input: "磁场转动", script: "search.js" },

        //Anime
        { title: "宝可梦", input: "宝可梦", script: "search.js" }, //Pokemon
        { title: "综漫", input: "综漫", script: "search.js" }, //Tổng mạn
        { title: "龙珠", input: "龙珠", script: "search.js" }, //Long châu
        { title: "火影", input: "火影", script: "search.js" }, //Hokage
        { title: "木叶", input: "火影", script: "search.js" }, //Konoha
        { title: "鸣人", input: "鸣人", script: "search.js" }, //Naruto
        { title: "犬夜叉", input: "犬夜叉", script: "search.js" }, //Inuyasha
        { title: "海贼", input: "海贼", script: "search.js" }, //Once piece
        { title: "妖尾", input: "妖尾", script: "search.js" }, //Fairy tail
        { title: "奥特曼", input: "奥特曼", script: "search.js" }, //Ultraman
        { title: "假面骑士", input: "假面骑士", script: "search.js" }, //Kamen rider
        { title: "骑士", input: "骑士", script: "search.js" }, //Rider
        { title: "死神", input: "死神", script: "search.js" }, //Bleach
        { title: "全職獵人", input: "全職獵人", script: "search.js" }, //HunterxHunter
        { title: "鬼灭之刃", input: "鬼灭之刃", script: "search.js" }, //Kimetsu no Yaiba
        { title: "美食", input: "美食", script: "search.js" }, //Toriko
        { title: "柯南", input: "柯南", script: "search.js" }, //Conan

		{title: "TOP bảng xếp hạng", input: `${BASE_URL}/api/author/misc/top_book_list/v1/`, script: "homecontent.js"},
		{title: "最新", input: "/api/author/library/book_list/v/?gender=1&category_id=704&creation_status=-1&word_count=-1&sort=1", script: "genrecontent.js"},
		{title: "最热", input: "/api/author/library/book_list/v/?gender=1&category_id=704&creation_status=-1&word_count=-1&sort=0", script: "genrecontent.js"},
		{title: "最热-已完结", input: "/api/author/library/book_list/v/?gender=1&category_id=704&creation_status=0&word_count=-1&sort=0", script: "genrecontent.js"},
		{title: "最热-连载中", input: "/api/author/library/book_list/v/?gender=1&category_id=704&creation_status=1&word_count=-1&sort=0", script: "genrecontent.js"},
		{title: "最新-已完结", input: "/api/author/library/book_list/v/?gender=1&category_id=704&creation_status=0&word_count=-1&sort=1", script: "genrecontent.js"},
		{title: "最新-连载中", input: "/api/author/library/book_list/v/?gender=1&category_id=704&creation_status=1&word_count=-1&sort=1", script: "genrecontent.js"},
		{title: "字数-已完结", input: "/api/author/library/book_list/v/?gender=1&category_id=704&creation_status=0&word_count=-1&sort=2", script: "genrecontent.js"},
		{"title": "Xuyên Qua", "input": "&tag=xuyenqua", "script": "tag.js"},
		{"title": "Hệ Thống", "input": "&tag=hethong", "script": "tag.js"},
		{"title": "Đô Thị", "input": "&tag=dothi", "script": "tag.js"},
		{"title": "Hiện Đại Ngôn Tình", "input": "&tag=hiendaingontinh", "script": "tag.js"},
		{"title": "Huyền Huyễn", "input": "&tag=huyenhuyen", "script": "tag.js"},
		{"title": "Cổ Đại Ngôn Tình", "input": "&tag=codaingontinh", "script": "tag.js"},
		{"title": "Trùng Sinh", "input": "&tag=trungsinh", "script": "tag.js"},
		{"title": "Đô Thị Não Động", "input": "&tag=dothinaodong", "script": "tag.js"},
		{"title": "Huyền Huyễn Não Động", "input": "&tag=huyenhuyennaodong", "script": "tag.js"},
		{"title": "Huyễn Tưởng Ngôn Tình", "input": "&tag=huyentuongngontinh", "script": "tag.js"},
		{"title": "Khoa Huyễn Tận Thế", "input": "&tag=khoahuyentanthe", "script": "tag.js"},
		{"title": "Kỳ Huyễn Tiên Hiệp", "input": "&tag=kyhuyentienhiep", "script": "tag.js"},
		{"title": "Sân Trường", "input": "&tag=santruong", "script": "tag.js"},
		{"title": "Lịch Sử", "input": "&tag=lichsu", "script": "tag.js"},
		{"title": "Nhị Thứ Nguyên", "input": "&tag=nhithunguyen", "script": "tag.js"},
		{"title": "Làm Ruộng", "input": "&tag=lamruong", "script": "tag.js"},
		{"title": "Không Gian", "input": "&tag=khonggian", "script": "tag.js"},
		{"title": "Song Nam Chính", "input": "&tag=songnamchinh", "script": "tag.js"},
		{"title": "Truyền Thống Huyền Huyễn", "input": "&tag=truyenthonghuyenhuyen", "script": "tag.js"},
		{"title": "Bá Tổng", "input": "&tag=batong", "script": "tag.js"},
		{"title": "Anime Diễn Sinh", "input": "&tag=animediensinh", "script": "tag.js"},
		{"title": "Nhanh Xuyên", "input": "&tag=nhanhxuyen", "script": "tag.js"},
		{"title": "Khoa Huyễn", "input": "&tag=khoahuyen", "script": "tag.js"},
		{"title": "Giả Heo Ăn Thịt Hổ", "input": "&tag=giaheoanthitho", "script": "tag.js"},
		{"title": "Trò Chơi Anime", "input": "&tag=trochoianime", "script": "tag.js"},
		{"title": "Ngành Giải Trí", "input": "&tag=nganhgiaitri", "script": "tag.js"},
		{"title": "Sủng Thê", "input": "&tag=sungthe", "script": "tag.js"},
		{"title": "Vô Địch", "input": "&tag=vodich", "script": "tag.js"},
		{"title": "Tận Thế", "input": "&tag=tanthe", "script": "tag.js"},
		{"title": "Linh Dị", "input": "&tag=linhdi", "script": "tag.js"},
		{"title": "Xấu Bụng", "input": "&tag=xaubung", "script": "tag.js"},
		{"title": "Huyền Nghi Não Động", "input": "&tag=huyennghinaodong", "script": "tag.js"},
		{"title": "Hào Môn Tổng Giám Đốc", "input": "&tag=haomontonggiamdoc", "script": "tag.js"},
		{"title": "Đô Thị Thường Ngày", "input": "&tag=dothithuongngay", "script": "tag.js"},
		{"title": "Huyền Huyễn Ngôn Tình", "input": "&tag=huyenhuyenngontinh", "script": "tag.js"},
		{"title": "Võ Hiệp", "input": "&tag=vohiep", "script": "tag.js"},
		{"title": "Thiên Tài", "input": "&tag=thientai", "script": "tag.js"},
		{"title": "Ngọt Sủng", "input": "&tag=ngotsung", "script": "tag.js"},
		{"title": "Đồng Nhân", "input": "&tag=dongnhan", "script": "tag.js"},
		{"title": "Huyền Nghi Linh Dị", "input": "&tag=huyennghilinhdi", "script": "tag.js"},
		{"title": "Hiện Lời Não Động", "input": "&tag=hienloinaodong", "script": "tag.js"},
		{"title": "Thanh Xuân Ngọt Sủng", "input": "&tag=thanhxuanngotsung", "script": "tag.js"},
		{"title": "Đơn Nữ Chính", "input": "&tag=donnuchinh", "script": "tag.js"},
		{"title": "Cùng Người", "input": "&tag=cungnguoi", "script": "tag.js"},
		{"title": "Cung Đấu Trạch Đấu", "input": "&tag=cungdautrachdau", "script": "tag.js"},
		{"title": "Niên Đại", "input": "&tag=niendai", "script": "tag.js"},
		{"title": "Xuyên Thư", "input": "&tag=xuyenthu", "script": "tag.js"},
		{"title": "Chư Thiên Vạn Giới", "input": "&tag=chuthienvangioi", "script": "tag.js"},
		{"title": "Đô Thị Tu Chân", "input": "&tag=dothituchan", "script": "tag.js"},
		{"title": "Nhân Vật Phản Diện", "input": "&tag=nhanvatphandien", "script": "tag.js"},
		{"title": "Mỹ Nữ", "input": "&tag=mynu", "script": "tag.js"},
		{"title": "Không Nữ Chính", "input": "&tag=khongnuchinh", "script": "tag.js"},
		{"title": "Trực Tiếp", "input": "&tag=tructiep", "script": "tag.js"},
		{"title": "Diễn Sinh Cùng Người", "input": "&tag=diensinhcungnguoi", "script": "tag.js"},
		{"title": "Lịch Sử Cổ Đại", "input": "&tag=lichsucodai", "script": "tag.js"},
		{"title": "Cầu Sinh", "input": "&tag=causinh", "script": "tag.js"},
		{"title": "Nữ Cường", "input": "&tag=nucuong", "script": "tag.js"},
		{"title": "Nam Tần Diễn Sinh", "input": "&tag=namtandiensinh", "script": "tag.js"},
		{"title": "Thần Hào", "input": "&tag=thanhao", "script": "tag.js"},
		{"title": "Đô Thị Cao Võ", "input": "&tag=dothicaovo", "script": "tag.js"},
		{"title": "Huyền Nghi", "input": "&tag=huyennghi", "script": "tag.js"},
		{"title": "Nữ Tần Diễn Sinh", "input": "&tag=nutandiensinh", "script": "tag.js"},
		{"title": "Diễn Sinh Đồng Nhân", "input": "&tag=diensinhdongnhan", "script": "tag.js"},
		{"title": "Lịch Sử Não Động", "input": "&tag=lichsunaodong", "script": "tag.js"},
		{"title": "Đô Thị Làm Ruộng", "input": "&tag=dothilamruong", "script": "tag.js"},
		{"title": "Không Cp", "input": "&tag=khongcp", "script": "tag.js"},
		{"title": "Đoàn Sủng", "input": "&tag=doansung", "script": "tag.js"},
		{"title": "Cổ Ngôn Não Động", "input": "&tag=congonnaodong", "script": "tag.js"},
		{"title": "Thần Y", "input": "&tag=thany", "script": "tag.js"},
		{"title": "Suy Luận", "input": "&tag=suyluan", "script": "tag.js"},
		{"title": "Trò Chơi Thể Dục", "input": "&tag=trochoitheduc", "script": "tag.js"},
		{"title": "Võng Du", "input": "&tag=vongdu", "script": "tag.js"},
		{"title": "Song Khiết", "input": "&tag=songkhiet", "script": "tag.js"},
		{"title": "Trò Chơi", "input": "&tag=trochoi", "script": "tag.js"},
		{"title": "Nông Thôn", "input": "&tag=nongthon", "script": "tag.js"},
		{"title": "Giáo Hoa", "input": "&tag=giaohoa", "script": "tag.js"},
		{"title": "Hai Nữ Chính", "input": "&tag=hainuchinh", "script": "tag.js"},
		{"title": "Manh Bảo", "input": "&tag=manhbao", "script": "tag.js"},
		{"title": "Hào Môn Sảng Văn", "input": "&tag=haomonsangvan", "script": "tag.js"},
		{"title": "Học Bá", "input": "&tag=hocba", "script": "tag.js"},
		{"title": "Tinh Tế", "input": "&tag=tinhte", "script": "tag.js"},
		{"title": "Tổng Giám Đốc", "input": "&tag=tonggiamdoc", "script": "tag.js"},
		{"title": "Kiếm Đạo", "input": "&tag=kiemdao", "script": "tag.js"},
		{"title": "Chiến Thần", "input": "&tag=chienthan", "script": "tag.js"},
		{"title": "Chỗ Làm Việc Tình Yêu Và Hôn Nhân", "input": "&tag=cholamviectinhyeuvahonnhan", "script": "tag.js"},
		{"title": "Huyền Nghi Yêu Nhau", "input": "&tag=huyennghiyeunhau", "script": "tag.js"},
		{"title": "Sủng Vật", "input": "&tag=sungvat", "script": "tag.js"},
		{"title": "Vô Hạn Lưu", "input": "&tag=vohanluu", "script": "tag.js"},
		{"title": "Hiện Lời Ngọt Sủng", "input": "&tag=hienloingotsung", "script": "tag.js"},
		{"title": "Hồng Hoang", "input": "&tag=honghoang", "script": "tag.js"},
		{"title": "Nữ Đế", "input": "&tag=nude", "script": "tag.js"},
		{"title": "Đông Phương Huyền Huyễn", "input": "&tag=dongphuonghuyenhuyen", "script": "tag.js"},
		{"title": "Ngược Văn", "input": "&tag=nguocvan", "script": "tag.js"},
		{"title": "Người Ở Rể", "input": "&tag=nguoiore", "script": "tag.js"},
		{"title": "Vương Phi", "input": "&tag=vuongphi", "script": "tag.js"},
		{"title": "Vú Em", "input": "&tag=vuem", "script": "tag.js"},
		{"title": "Trộm Mộ", "input": "&tag=trommo", "script": "tag.js"},
		{"title": "Đô Thị Dị Năng", "input": "&tag=dothidinang", "script": "tag.js"},
		{"title": "Dị Thế Đại Lục", "input": "&tag=dithedailuc", "script": "tag.js"},
		{"title": "Khôi Hài Nhẹ Nhõm", "input": "&tag=khoihainhenhom", "script": "tag.js"},
		{"title": "Công Chúa", "input": "&tag=congchua", "script": "tag.js"},
		{"title": "Tam Quốc", "input": "&tag=tamquoc", "script": "tag.js"},
		{"title": "Thể Dục", "input": "&tag=theduc", "script": "tag.js"},
		{"title": "Thanh Mai Trúc Mã", "input": "&tag=thanhmaitrucma", "script": "tag.js"},
		{"title": "Hải Tặc", "input": "&tag=haitac", "script": "tag.js"},
		{"title": "Đích Nữ", "input": "&tag=dichnu", "script": "tag.js"},
		{"title": "Diễn Sinh", "input": "&tag=diensinh", "script": "tag.js"},
		{"title": "Mỹ Thực", "input": "&tag=mythuc", "script": "tag.js"},
		{"title": "Tổng Truyền Hình Điện Ảnh", "input": "&tag=tongtruyenhinhdienanh", "script": "tag.js"},
		{"title": "Áo Lót", "input": "&tag=aolot", "script": "tag.js"},
		{"title": "Tình Yêu Và Hôn Nhân", "input": "&tag=tinhyeuvahonnhan", "script": "tag.js"},
		{"title": "Gia Đình", "input": "&tag=giadinh", "script": "tag.js"},
		{"title": "Chỗ Làm Việc", "input": "&tag=cholamviec", "script": "tag.js"},
		{"title": "Phá Án", "input": "&tag=phaan", "script": "tag.js"},
		{"title": "Lính Đặc Chủng", "input": "&tag=linhdacchung", "script": "tag.js"},
		{"title": "Minh Triều", "input": "&tag=minhtrieu", "script": "tag.js"},
		{"title": "Đại Đường", "input": "&tag=daiduong", "script": "tag.js"},
		{"title": "Y Thuật", "input": "&tag=ythuat", "script": "tag.js"},
		{"title": "Thuần Ái", "input": "&tag=thuanai", "script": "tag.js"},
		{"title": "Giám Giám", "input": "&tag=giamgiam", "script": "tag.js"},
		{"title": "Môn Môn", "input": "&tag=monmon", "script": "tag.js"},
		{"title": "Giám Bảo", "input": "&tag=giambao", "script": "tag.js"},
		{"title": "Thống Thống", "input": "&tag=thongthong", "script": "tag.js"},
		{"title": "Chiến Thần Người Ở Rể", "input": "&tag=chienthannguoiore", "script": "tag.js"},
		{"title": "Qua Qua", "input": "&tag=quaqua", "script": "tag.js"},
		{"title": "Bệnh Kiều", "input": "&tag=benhkieu", "script": "tag.js"},
		{"title": "Lâu Ngày Sinh Tình", "input": "&tag=laungaysinhtinh", "script": "tag.js"},
		{"title": "Dị Thế Xuyên Qua", "input": "&tag=dithexuyenqua", "script": "tag.js"},
		{"title": "Tây Du", "input": "&tag=taydu", "script": "tag.js"},
		{"title": "Nữ Giả Nam Trang", "input": "&tag=nugianamtrang", "script": "tag.js"},
		{"title": "Động Động", "input": "&tag=dongdong", "script": "tag.js"},
		{"title": "Giá Không", "input": "&tag=giakhong", "script": "tag.js"},
		{"title": "Hải Đảo", "input": "&tag=haidao", "script": "tag.js"},
		{"title": "Huyễn Huyễn", "input": "&tag=huyenhuyen", "script": "tag.js"},
		{"title": "Tinh Linh", "input": "&tag=tinhlinh", "script": "tag.js"},
		{"title": "Cuộc Sống Đô Thị", "input": "&tag=cuocsongdothi", "script": "tag.js"},
		{"title": "Hậu Cung", "input": "&tag=haucung", "script": "tag.js"},
		{"title": "Linh Khí Khôi Phục", "input": "&tag=linhkhikhoiphuc", "script": "tag.js"},
		{"title": "Kháng Chiến Chiến Tranh Tình Báo", "input": "&tag=khangchienchientranhtinhbao", "script": "tag.js"},
		{"title": "Auth Đồng Nhân", "input": "&tag=authdongnhan", "script": "tag.js"},
		{"title": "Chiến Chiến", "input": "&tag=chienchien", "script": "tag.js"},
		{"title": "Tranh Tranh", "input": "&tag=tranhtranh", "script": "tag.js"},
		{"title": "Báo Báo", "input": "&tag=baobao", "script": "tag.js"},
		{"title": "Cao Võ Thế Giới", "input": "&tag=caovothegioi", "script": "tag.js"},
		{"title": "Đại Tần", "input": "&tag=daitan", "script": "tag.js"},
		{"title": "Tinh Quang Thôi Xán", "input": "&tag=tinhquangthoixan", "script": "tag.js"},
		{"title": "Tình Tình", "input": "&tag=tinhtinh", "script": "tag.js"},
		{"title": "Hiện Lời Thường Ngày", "input": "&tag=hienloithuongngay", "script": "tag.js"},
		{"title": "Trước Tiên Cưới Sau Thích", "input": "&tag=truoctiencuoisauthich", "script": "tag.js"},
		{"title": "Hoàng Hậu", "input": "&tag=hoanghau", "script": "tag.js"},
		{"title": "Auth Cùng Người", "input": "&tag=authcungnguoi", "script": "tag.js"},
		{"title": "Chat Group", "input": "&tag=chatgroup", "script": "tag.js"},
		{"title": "Thị Thị", "input": "&tag=thithi", "script": "tag.js"},
		{"title": "Nhân Nhân", "input": "&tag=nhannhan", "script": "tag.js"},
		{"title": "Làm Làm", "input": "&tag=lamlam", "script": "tag.js"},
		{"title": "Dân Quốc Ngôn Tình", "input": "&tag=danquocngontinh", "script": "tag.js"},
		{"title": "Và Và", "input": "&tag=vava", "script": "tag.js"},
		{"title": "Cửu Thúc", "input": "&tag=cuuthuc", "script": "tag.js"},
		{"title": "Truyền Hình Điện Ảnh", "input": "&tag=truyenhinhdienanh", "script": "tag.js"},
		{"title": "Thú Thế", "input": "&tag=thuthe", "script": "tag.js"},
		{"title": "Độc Sủng", "input": "&tag=docsung", "script": "tag.js"},
		{"title": "Chuyển Phát Nhanh", "input": "&tag=chuyenphatnhanh", "script": "tag.js"},
		{"title": "Chơi Chơi", "input": "&tag=choichoi", "script": "tag.js"},
		{"title": "Chạy Nạn", "input": "&tag=chaynan", "script": "tag.js"},
		{"title": "Quân Hôn", "input": "&tag=quanhon", "script": "tag.js"},
		{"title": "Tổng Mạn", "input": "&tag=tongman", "script": "tag.js"},
		{"title": "Văn Học Mạng - Quan Trường", "input": "&tag=vanhocmangquantruong", "script": "tag.js"},
		{"title": "Dân Quốc", "input": "&tag=danquoc", "script": "tag.js"},
		{"title": "Thanh Xuyên", "input": "&tag=thanhxuyen", "script": "tag.js"},
		{"title": "Long Châu", "input": "&tag=longchau", "script": "tag.js"},
		{"title": "Tiên Tiên", "input": "&tag=tientien", "script": "tag.js"},
		{"title": "Sau Sau", "input": "&tag=sausau", "script": "tag.js"},
		{"title": "Phong Hiểm Đồng Nhân", "input": "&tag=phonghiemdongnhan", "script": "tag.js"},
		{"title": "Xuyên Xuyên", "input": "&tag=xuyenxuyen", "script": "tag.js"},
		{"title": "Hiện Đại", "input": "&tag=hiendai", "script": "tag.js"},
		{"title": "Hào Môn Thế Gia", "input": "&tag=haomonthegia", "script": "tag.js"},
		{"title": "Tận Thế Cầu Sinh", "input": "&tag=tanthecausinh", "script": "tag.js"},
		{"title": "Đại Lão", "input": "&tag=dailao", "script": "tag.js"},
		{"title": "Đại Đại", "input": "&tag=daidai", "script": "tag.js"},
		{"title": "Thần Thần", "input": "&tag=thanthan", "script": "tag.js"},
		{"title": "Sinh Sinh", "input": "&tag=sinhsinh", "script": "tag.js"},
		{"title": "Hệ Hệ", "input": "&tag=hehe", "script": "tag.js"},
		{"title": "Nhị Nhị", "input": "&tag=nhinhi", "script": "tag.js"},
		{"title": "Nguyên Nguyên", "input": "&tag=nguyennguyen", "script": "tag.js"},
		{"title": "Bắt Đầu", "input": "&tag=batdau", "script": "tag.js"},
		{"title": "Ở Ở", "input": "&tag=oo", "script": "tag.js"},
		{"title": "Nhiều Nữ Chính", "input": "&tag=nhieunuchinh", "script": "tag.js"},
		{"title": "Thiên Tai", "input": "&tag=thientai", "script": "tag.js"},
		{"title": "Võ Hồn", "input": "&tag=vohon", "script": "tag.js"},
		{"title": "Cổ Đại", "input": "&tag=codai", "script": "tag.js"},
		{"title": "Trảm Thần Diễn Sinh", "input": "&tag=tramthandiensinh", "script": "tag.js"},
		{"title": "Văn Học", "input": "&tag=vanhoc", "script": "tag.js"},
		{"title": "Nhân Văn Xã Khoa", "input": "&tag=nhanvanxakhoa", "script": "tag.js"},
		{"title": "Triết Học Tông Giáo", "input": "&tag=triethoctonggiao", "script": "tag.js"},
		{"title": "Ruộng Ruộng", "input": "&tag=ruongruong", "script": "tag.js"},
		{"title": "Thiên Thiên", "input": "&tag=thienthien", "script": "tag.js"},
		{"title": "Tỷ Tỷ Lưu", "input": "&tag=tytyluu", "script": "tag.js"},
		{"title": "Hiệp Hiệp", "input": "&tag=hiephiep", "script": "tag.js"},
		{"title": "Giới Giới", "input": "&tag=gioigioi", "script": "tag.js"},
		{"title": "Trước Tiên Cưới Sau Yêu", "input": "&tag=truoctiencuoisauyeu", "script": "tag.js"},
		{"title": "Khác - Cùng Người", "input": "&tag=khaccungnguoi", "script": "tag.js"},
		{"title": "Tây Du Diễn Sinh", "input": "&tag=taydudiensinh", "script": "tag.js"},
		{"title": "Hoàng Thúc", "input": "&tag=hoangthuc", "script": "tag.js"},
		{"title": "Chỗ Làm Việc Thương Chiến", "input": "&tag=cholamviecthuongchien", "script": "tag.js"},
		{"title": "Cường Cường", "input": "&tag=cuongcuong", "script": "tag.js"},
		{"title": "Sử Sử", "input": "&tag=susu", "script": "tag.js"},
		{"title": "Sinh Hoạt", "input": "&tag=sinhhoat", "script": "tag.js"},
		{"title": "Hoang Hoang", "input": "&tag=hoanghoang", "script": "tag.js"},
		{"title": "Ông Trời Tác Hợp Cho", "input": "&tag=ongtroitachopcho", "script": "tag.js"},
		{"title": "Đại Tiểu Thư", "input": "&tag=daitieuthu", "script": "tag.js"},
		{"title": "Quỷ Phu", "input": "&tag=quyphu", "script": "tag.js"},
		{"title": "Thầm Mến", "input": "&tag=thammen", "script": "tag.js"},
		{"title": "Vật Vật", "input": "&tag=vatvat", "script": "tag.js"},
		{"title": "Heo Heo", "input": "&tag=heoheo", "script": "tag.js"},
		{"title": "Kinh Dị Trò Chơi", "input": "&tag=kinhditrochoi", "script": "tag.js"},
		{"title": "Thịt Thịt", "input": "&tag=thitthit", "script": "tag.js"},
		{"title": "Âm Vợ", "input": "&tag=amvo", "script": "tag.js"},
		{"title": "Cổ Ngôn Ngọt Sủng", "input": "&tag=congonngotsung", "script": "tag.js"},
		{"title": "Nam Tần - Song Nam Chính", "input": "&tag=namtansongnamchinh", "script": "tag.js"},
		{"title": "Thành Công Dốc Lòng", "input": "&tag=thanhcongdoclong", "script": "tag.js"},
		{"title": "Quốc Vận", "input": "&tag=quocvan", "script": "tag.js"},
		{"title": "Phong Hiểm Cùng Người", "input": "&tag=phonghiemcungnguoi", "script": "tag.js"},
		{"title": "Văn Học Kinh Điển", "input": "&tag=vanhockinhdien", "script": "tag.js"},
		{"title": "Chiến Tranh Tình Báo", "input": "&tag=chientranhtinhbao", "script": "tag.js"},
		{"title": "Hào Hào", "input": "&tag=haohao", "script": "tag.js"},
		{"title": "Võ Tướng", "input": "&tag=votuong", "script": "tag.js"},
		{"title": "Cổ Đại Văn Học", "input": "&tag=codaivanhoc", "script": "tag.js"},
		{"title": "Song Hướng Lao Tới", "input": "&tag=songhuonglaotoi", "script": "tag.js"},
		{"title": "Tài Tài", "input": "&tag=taitai", "script": "tag.js"},
		{"title": "Kiếp Trước Và Kiếp Này", "input": "&tag=kieptruocvakiepnay", "script": "tag.js"},
		{"title": "Địch Địch", "input": "&tag=dichdich", "script": "tag.js"},
		{"title": "Tiếp Tiếp", "input": "&tag=tieptiep", "script": "tag.js"},
		{"title": "Kinh Tế Quản Lý", "input": "&tag=kinhtequanly", "script": "tag.js"},
		{"title": "Văn Học Mạng - Xuất Bản", "input": "&tag=vanhocmangxuatban", "script": "tag.js"},
		{"title": "Giáo Dục", "input": "&tag=giaoduc", "script": "tag.js"},
		{"title": "Gian Gian", "input": "&tag=giangian", "script": "tag.js"},
		{"title": "Diện Diện", "input": "&tag=diendien", "script": "tag.js"},
		{"title": "Lịch Lịch", "input": "&tag=lichlich", "script": "tag.js"},
		{"title": "Bụng Bụng", "input": "&tag=bungbung", "script": "tag.js"},
		{"title": "Hắc Đạo", "input": "&tag=hacdao", "script": "tag.js"},
		{"title": "Đế Đế", "input": "&tag=dede", "script": "tag.js"},
		{"title": "Cổ Linh Tinh Quái", "input": "&tag=colinhtinhquai", "script": "tag.js"},
		{"title": "Ngoại Quốc Văn Học", "input": "&tag=ngoaiquocvanhoc", "script": "tag.js"},
		{"title": "Cá Nhân Trưởng Thành", "input": "&tag=canhantruongthanh", "script": "tag.js"},
		{"title": "Đô Thị Thanh Xuân", "input": "&tag=dothithanhxuan", "script": "tag.js"},
		{"title": "Nữ Nữ", "input": "&tag=nunu", "script": "tag.js"},
		{"title": "Công Bản Diễn Sinh", "input": "&tag=congbandiensinh", "script": "tag.js"},
		{"title": "Thơ Ca Văn Xuôi", "input": "&tag=thocavanxuoi", "script": "tag.js"},
		{"title": "Văn Hóa Lịch Sử", "input": "&tag=vanhoalichsu", "script": "tag.js"},
		{"title": "Lời Lời", "input": "&tag=loiloi", "script": "tag.js"},
		{"title": "Chiến Tranh", "input": "&tag=chientranh", "script": "tag.js"},
		{"title": "Chân Chân", "input": "&tag=chanchan", "script": "tag.js"},
		{"title": "Tinh Phẩm", "input": "&tag=tinhpham", "script": "tag.js"},
		{"title": "Sủng Sủng", "input": "&tag=sungsung", "script": "tag.js"},
		{"title": "Kinh Điển Quốc Học", "input": "&tag=kinhdienquochoc", "script": "tag.js"},
		{"title": "Trùng Trùng", "input": "&tag=trungtrung", "script": "tag.js"},
		{"title": "Đạo Đạo", "input": "&tag=daodao", "script": "tag.js"},
		{"title": "Tứ Hợp Viện", "input": "&tag=tuhopvien", "script": "tag.js"},
		{"title": "Đứt Gãy", "input": "&tag=dutgay", "script": "tag.js"},
		{"title": "Quốc Quốc", "input": "&tag=quocquoc", "script": "tag.js"},
		{"title": "Song Diện", "input": "&tag=songdien", "script": "tag.js"},
		{"title": "Chân Huyên Diễn Sinh", "input": "&tag=chanhuyendiensinh", "script": "tag.js"},
		{"title": "Đánh Mặt", "input": "&tag=danhmat", "script": "tag.js"},
		{"title": "Hồng Lâu Diễn Sinh", "input": "&tag=honglaudiensinh", "script": "tag.js"},
		{"title": "Như Ý Diễn Sinh", "input": "&tag=nhuydiensinh", "script": "tag.js"},
		{"title": "Thứ Thứ", "input": "&tag=thuthu", "script": "tag.js"},
		{"title": "Thần Thám", "input": "&tag=thantham", "script": "tag.js"},
		{"title": "Thế Thế", "input": "&tag=thethe", "script": "tag.js"},
		{"title": "Vừa Thấy Đã Yêu", "input": "&tag=vuathaydayeu", "script": "tag.js"},
		{"title": "Tống Triều", "input": "&tag=tongtrieu", "script": "tag.js"},
		{"title": "Có Thể Muối Có Thể Ngọt", "input": "&tag=cothemuoicothengot", "script": "tag.js"},
		{"title": "Minh Tinh", "input": "&tag=minhtinh", "script": "tag.js"},
		{"title": "Ngôn Ngôn", "input": "&tag=ngonngon", "script": "tag.js"},
		{"title": "Y Y", "input": "&tag=yy", "script": "tag.js"},
		{"title": "Nghi Nghi", "input": "&tag=nghinghi", "script": "tag.js"},
		{"title": "Khác - Đồng Nhân", "input": "&tag=khacdongnhan", "script": "tag.js"},
		{"title": "Dễ Giận", "input": "&tag=degian", "script": "tag.js"},
		{"title": "Mười Ngày Diễn Sinh", "input": "&tag=muoingaydiensinh", "script": "tag.js"},
		{"title": "Bác Sĩ", "input": "&tag=bacsi", "script": "tag.js"},
		{"title": "Võng Võng", "input": "&tag=vongvong", "script": "tag.js"},
		{"title": "Thanh Triều", "input": "&tag=thanhtrieu", "script": "tag.js"},
		{"title": "Hoa Hoa", "input": "&tag=hoahoa", "script": "tag.js"},
		{"title": "Dị Dị", "input": "&tag=didi", "script": "tag.js"},
		{"title": "Đấu Đấu", "input": "&tag=daudau", "script": "tag.js"},
		{"title": "Cổ Tịch", "input": "&tag=cotich", "script": "tag.js"},
		{"title": "Giải Giải", "input": "&tag=giaigiai", "script": "tag.js"},
		{"title": "Hoàng Đế", "input": "&tag=hoangde", "script": "tag.js"},
		{"title": "Tông Giáo", "input": "&tag=tonggiao", "script": "tag.js"},
		{"title": "Tặc Tặc", "input": "&tag=tactac", "script": "tag.js"},
		{"title": "Tương Ái Tương Sát", "input": "&tag=tuongaituongsat", "script": "tag.js"},
		{"title": "Nay Xuyên Cổ", "input": "&tag=nayxuyenco", "script": "tag.js"},
		{"title": "Tưởng Tưởng", "input": "&tag=tuongtuong", "script": "tag.js"},
		{"title": "Phong Thần", "input": "&tag=phongthan", "script": "tag.js"},
		{"title": "Cuộc Sống Thực Tế", "input": "&tag=cuocsongthucte", "script": "tag.js"},
		{"title": "Gương Vỡ Lại Lành", "input": "&tag=guongvolailanh", "script": "tag.js"},
		{"title": "Nhân Vật Truyền Kỳ", "input": "&tag=nhanvattruyenky", "script": "tag.js"},
		{"title": "Em Em", "input": "&tag=emem", "script": "tag.js"},
		{"title": "Tình Cảm", "input": "&tag=tinhcam", "script": "tag.js"},
		{"title": "Băng Sơn", "input": "&tag=bangson", "script": "tag.js"},
		{"title": "Đồng Đồng", "input": "&tag=dongdong", "script": "tag.js"},
		{"title": "Lịch Sử Truyện Ký", "input": "&tag=lichsutruyenky", "script": "tag.js"},
		{"title": "Khoa Học Kỹ Thuật", "input": "&tag=khoahockythuat", "script": "tag.js"},
		{"title": "Huyền Nghi Suy Luận", "input": "&tag=huyennghisuyluan", "script": "tag.js"},
		{"title": "Chư Chư", "input": "&tag=chuchu", "script": "tag.js"},
		{"title": "Vạn Vạn", "input": "&tag=vanvan", "script": "tag.js"},
		{"title": "Văn Hóa Nghệ Thuật", "input": "&tag=vanhoanghethuat", "script": "tag.js"},
		{"title": "Song Trọng Sinh", "input": "&tag=songtrongsinh", "script": "tag.js"},
		{"title": "Tướng Quân", "input": "&tag=tuongquan", "script": "tag.js"},
		{"title": "Du Du", "input": "&tag=dudu", "script": "tag.js"},
		{"title": "Trung Quốc Tác Phẩm Nổi Tiếng", "input": "&tag=trungquoctacphamnoitieng", "script": "tag.js"},
		{"title": "Trung Quốc Văn Học", "input": "&tag=trungquocvanhoc", "script": "tag.js"},
		{"title": "Quân Sự", "input": "&tag=quansu", "script": "tag.js"},
		{"title": "Trò Chơi Chủ Bá", "input": "&tag=trochoichuba", "script": "tag.js"},
		{"title": "Cổ Ngôn Manh Bảo", "input": "&tag=congonmanhbao", "script": "tag.js"},
		{"title": "Vô Vô", "input": "&tag=vovo", "script": "tag.js"},
		{"title": "Auth Auth", "input": "&tag=authauth", "script": "tag.js"},
		{"title": "Hokage Hokage", "input": "&tag=hokagehokage", "script": "tag.js"},
		{"title": "Sinh Hoạt Bách Khoa", "input": "&tag=sinhhoatbachkhoa", "script": "tag.js"},
		{"title": "Đặc Công", "input": "&tag=daccong", "script": "tag.js"},
		{"title": "Đường Đường", "input": "&tag=duongduong", "script": "tag.js"},
		{"title": "Điện Cạnh", "input": "&tag=diencanh", "script": "tag.js"},
		{"title": "Bảo Bảo", "input": "&tag=baobao", "script": "tag.js"},
		{"title": "Giả Giả", "input": "&tag=giagia", "script": "tag.js"},
		{"title": "Ăn Ăn", "input": "&tag=anan", "script": "tag.js"},
		{"title": "Ngược Cặn Bã", "input": "&tag=nguoccanba", "script": "tag.js"},
		{"title": "Sống Sống", "input": "&tag=songsong", "script": "tag.js"},
		{"title": "Hổ Hổ", "input": "&tag=hoho", "script": "tag.js"},
		{"title": "Mộ Mộ", "input": "&tag=momo", "script": "tag.js"},
		{"title": "Thân Tử Gia Giáo", "input": "&tag=thantugiagiao", "script": "tag.js"},
		{"title": "Thê Thê", "input": "&tag=thethe", "script": "tag.js"},
		{"title": "Giáo Dục Dành Cho Người Lớn", "input": "&tag=giaoducdanhchonguoilon", "script": "tag.js"},
		{"title": "Tình Hữu Độc Chung", "input": "&tag=tinhhuudocchung", "script": "tag.js"},
		{"title": "Hải Hải", "input": "&tag=haihai", "script": "tag.js"},
		{"title": "Hiện Hiện", "input": "&tag=hienhien", "script": "tag.js"},
		{"title": "Tế Tế", "input": "&tag=tete", "script": "tag.js"},
		{"title": "Trường Trường", "input": "&tag=truongtruong", "script": "tag.js"},
		{"title": "Châu Châu", "input": "&tag=chauchau", "script": "tag.js"},
		{"title": "Thư Thư", "input": "&tag=thuthu", "script": "tag.js"},
		{"title": "Chúa Chúa", "input": "&tag=chuachua", "script": "tag.js"},
		{"title": "Kinh Khủng Chạy Trốn", "input": "&tag=kinhkhungchaytron", "script": "tag.js"},
		{"title": "Độc Y", "input": "&tag=docy", "script": "tag.js"},
		{"title": "Bảo Vệ Sức Khoẻ Dưỡng Sinh", "input": "&tag=baovesuckhoeduongsinh", "script": "tag.js"},
		{"title": "Thực Thực", "input": "&tag=thucthuc", "script": "tag.js"},
		{"title": "Tinh Tiến Đề Thăng", "input": "&tag=tinhtiendethang", "script": "tag.js"},
		{"title": "Tần Tần", "input": "&tag=tantan", "script": "tag.js"},
		{"title": "Thế Thân", "input": "&tag=thethan", "script": "tag.js"},
		{"title": "Dốc Lòng Đề Thăng", "input": "&tag=doclongdethang", "script": "tag.js"},
		{"title": "Chính Trị Quân Sự", "input": "&tag=chinhtriquansu", "script": "tag.js"},
		{"title": "Tận Tận", "input": "&tag=tantan", "script": "tag.js"},
		{"title": "Hiện Kéo Dài", "input": "&tag=hienkeodai", "script": "tag.js"},
		{"title": "Khoa Học Xã Hội", "input": "&tag=khoahocxahoi", "script": "tag.js"},
		{"title": "Cung Đình Hầu Tước", "input": "&tag=cungdinhhautuoc", "script": "tag.js"},
		{"title": "Huyền Huyễn Sảng Văn", "input": "&tag=huyenhuyensangvan", "script": "tag.js"},
		{"title": "Tổng Tổng", "input": "&tag=tongtong", "script": "tag.js"},
		{"title": "Đốc Đốc", "input": "&tag=docdoc", "script": "tag.js"},
		{"title": "Phong Thuỷ Xem Bói", "input": "&tag=phongthuyxemboi", "script": "tag.js"},
		{"title": "Chính Chính", "input": "&tag=chinhchinh", "script": "tag.js"},
		{"title": "Xuân Xuân", "input": "&tag=xuanxuan", "script": "tag.js"},
		{"title": "Nguyên Thần", "input": "&tag=nguyenthan", "script": "tag.js"},
		{"title": "Đẩy Sách", "input": "&tag=daysach", "script": "tag.js"},
		{"title": "Ngày Ngày", "input": "&tag=ngayngay", "script": "tag.js"},
		{"title": "Đô Đô", "input": "&tag=dodo", "script": "tag.js"},
		{"title": "Bá Bá", "input": "&tag=baba", "script": "tag.js"},
		{"title": "Xấu Xấu", "input": "&tag=xauxau", "script": "tag.js"},
		{"title": "Triều Triều", "input": "&tag=trieutrieu", "script": "tag.js"},
		{"title": "Vận Động Kiện Thân", "input": "&tag=vandongkienthan", "script": "tag.js"},
		{"title": "Phẩm Phẩm", "input": "&tag=phampham", "script": "tag.js"},
		{"title": "Tiếng Tiếng", "input": "&tag=tiengtieng", "script": "tag.js"},
		{"title": "Bao Che Khuyết Điểm", "input": "&tag=baochekhuyetdiem", "script": "tag.js"},
		{"title": "Phi Phi", "input": "&tag=phiphi", "script": "tag.js"},
		{"title": "Huyền Huyễn Xuyên Qua", "input": "&tag=huyenhuyenxuyenqua", "script": "tag.js"},
		{"title": "Tâm Lý Học", "input": "&tag=tamlyhoc", "script": "tag.js"},
		{"title": "Trung Quốc Lịch Sử", "input": "&tag=trungquoclichsu", "script": "tag.js"},
		{"title": "Quốc Nội Truyền Hình Điện Ảnh", "input": "&tag=quocnoitruyenhinhdienanh", "script": "tag.js"},
		{"title": "Hạn Hạn", "input": "&tag=hanhan", "script": "tag.js"},
		{"title": "Cầu Cầu", "input": "&tag=caucau", "script": "tag.js"},
		{"title": "Thế Giới Tác Phẩm Nổi Tiếng", "input": "&tag=thegioitacphamnoitieng", "script": "tag.js"},
		{"title": "Huyền Huyễn Hệ Thống", "input": "&tag=huyenhuyenhethong", "script": "tag.js"},
		{"title": "Vệ Vệ", "input": "&tag=veve", "script": "tag.js"},
		{"title": "Khoẻ Khoẻ", "input": "&tag=khoekhoe", "script": "tag.js"},
		{title: "字数-连载中", input: "/api/author/library/book_list/v/?gender=1&category_id=704&creation_status=1&word_count=-1&sort=2", script: "genrecontent.js"},
		{ "title": "女频悬疑", "input": "/api/author/library/book_list/v0/?category_id=747", "script": "genrecontent.js" },
		{ "title": "西方奇幻", "input": "/api/author/library/book_list/v0/?category_id=1141", "script": "genrecontent.js" },
		{ "title": "东方仙侠", "input": "/api/author/library/book_list/v0/?category_id=1140", "script": "genrecontent.js" },
		{ "title": "古风世情", "input": "/api/author/library/book_list/v0/?category_id=1139", "script": "genrecontent.js" },
		{ "title": "科幻末世", "input": "/api/author/library/book_list/v0/?category_id=8", "script": "genrecontent.js" },
		{ "title": "男频衍生", "input": "/api/author/library/book_list/v0/?category_id=1016", "script": "genrecontent.js" },
		{ "title": "女频衍生", "input": "/api/author/library/book_list/v0/?category_id=1015", "script": "genrecontent.js" },
		{ "title": "民国言情", "input": "/api/author/library/book_list/v0/?category_id=1017", "script": "genrecontent.js" },
		{ "title": "都市高武", "input": "/api/author/library/book_list/v0/?category_id=1014", "script": "genrecontent.js" },
		{ "title": "悬疑灵异", "input": "/api/author/library/book_list/v0/?category_id=751", "script": "genrecontent.js" },
		{ "title": "悬疑脑洞", "input": "/api/author/library/book_list/v0/?category_id=539", "script": "genrecontent.js" },
		{ "title": "抗战谍战", "input": "/api/author/library/book_list/v0/?category_id=504", "script": "genrecontent.js" },
		{ "title": "青春甜宠", "input": "/api/author/library/book_list/v0/?category_id=749", "script": "genrecontent.js" },
		{ "title": "双男主", "input": "/api/author/library/book_list/v0/?category_id=275", "script": "genrecontent.js" },
		{ "title": "古言脑洞", "input": "/api/author/library/book_list/v0/?category_id=253", "script": "genrecontent.js" },
		{ "title": "历史古代", "input": "/api/author/library/book_list/v0/?category_id=273", "script": "genrecontent.js" },
		{ "title": "历史脑洞", "input": "/api/author/library/book_list/v0/?category_id=272", "script": "genrecontent.js" },
		{ "title": "现言脑洞", "input": "/api/author/library/book_list/v0/?category_id=267", "script": "genrecontent.js" },
		{ "title": "都市种田", "input": "/api/author/library/book_list/v0/?category_id=263", "script": "genrecontent.js" },
		{ "title": "都市脑洞", "input": "/api/author/library/book_list/v0/?category_id=262", "script": "genrecontent.js" },
		{ "title": "都市日常", "input": "/api/author/library/book_list/v0/?category_id=261", "script": "genrecontent.js" },
		{ "title": "玄幻脑洞", "input": "/api/author/library/book_list/v0/?category_id=257", "script": "genrecontent.js" },
		{ "title": "玄幻言情", "input": "/api/author/library/book_list/v0/?category_id=248", "script": "genrecontent.js" },
		{ "title": "宫斗宅斗", "input": "/api/author/library/book_list/v0/?category_id=246", "script": "genrecontent.js" },
		{ "title": "豪门总裁", "input": "/api/author/library/book_list/v0/?category_id=748", "script": "genrecontent.js" },
		{ "title": "战神赘婿", "input": "/api/author/library/book_list/v0/?category_id=27", "script": "genrecontent.js" },
		{ "title": "动漫衍生", "input": "/api/author/library/book_list/v0/?category_id=718", "script": "genrecontent.js" },
		{ "title": "星光璀璨", "input": "/api/author/library/book_list/v0/?category_id=745", "script": "genrecontent.js" },
		{ "title": "游戏体育", "input": "/api/author/library/book_list/v0/?category_id=746", "script": "genrecontent.js" },
		{ "title": "职场婚恋", "input": "/api/author/library/book_list/v0/?category_id=750", "script": "genrecontent.js" },
		{ "title": "双女主", "input": "/api/author/library/book_list/v0/?category_id=704", "script": "genrecontent.js" },
		{ "title": "传统玄幻", "input": "/api/author/library/book_list/v0/?category_id=258", "script": "genrecontent.js" },
		{ "title": "都市修真", "input": "/api/author/library/book_list/v0/?category_id=124", "script": "genrecontent.js" },
		{ "title": "年代", "input": "/api/author/library/book_list/v0/?category_id=79", "script": "genrecontent.js" },
		{ "title": "种田", "input": "/api/author/library/book_list/v0/?category_id=23", "script": "genrecontent.js" },
		{ "title": "快穿", "input": "/api/author/library/book_list/v0/?category_id=24", "script": "genrecontent.js" },
		{ "title": "古言权谋", "input": "/api/author/library/book_list/v0/?category_id=1317", "script": "genrecontent.js" },
		{ "title": "悬疑恋爱", "input": "/api/author/library/book_list/v0/?category_id=1169", "script": "genrecontent.js" },
		{ "title": "纯爱", "input": "/api/author/library/book_list/v0/?category_id=1012", "script": "genrecontent.js" },
		{ "title": "衍生", "input": "/api/author/library/book_list/v0/?category_id=1079", "script": "genrecontent.js" },
		{ "title": "仕途", "input": "/api/author/library/book_list/v0/?category_id=558", "script": "genrecontent.js" },
		{ "title": "综影视", "input": "/api/author/library/book_list/v0/?category_id=1058", "script": "genrecontent.js" },
		{ "title": "天灾", "input": "/api/author/library/book_list/v0/?category_id=658", "script": "genrecontent.js" },
		{ "title": "第一人称", "input": "/api/author/library/book_list/v0/?category_id=871", "script": "genrecontent.js" },
		{ "title": "赛博朋克", "input": "/api/author/library/book_list/v0/?category_id=873", "script": "genrecontent.js" },
		{ "title": "第四天灾", "input": "/api/author/library/book_list/v0/?category_id=855", "script": "genrecontent.js" },
		{ "title": "规则怪谈", "input": "/api/author/library/book_list/v0/?category_id=851", "script": "genrecontent.js" },
		{ "title": "古代", "input": "/api/author/library/book_list/v0/?category_id=758", "script": "genrecontent.js" },
		{ "title": "悬疑", "input": "/api/author/library/book_list/v0/?category_id=10", "script": "genrecontent.js" },
		{ "title": "克苏鲁", "input": "/api/author/library/book_list/v0/?category_id=705", "script": "genrecontent.js" },
		{ "title": "都市异能", "input": "/api/author/library/book_list/v0/?category_id=516", "script": "genrecontent.js" },
		{ "title": "末日求生", "input": "/api/author/library/book_list/v0/?category_id=515", "script": "genrecontent.js" },
		{ "title": "灵气复苏", "input": "/api/author/library/book_list/v0/?category_id=514", "script": "genrecontent.js" },
		{ "title": "高武世界", "input": "/api/author/library/book_list/v0/?category_id=513", "script": "genrecontent.js" },
		{ "title": "异世大陆", "input": "/api/author/library/book_list/v0/?category_id=512", "script": "genrecontent.js" },
		{ "title": "东方玄幻", "input": "/api/author/library/book_list/v0/?category_id=511", "script": "genrecontent.js" },
		{ "title": "谍战", "input": "/api/author/library/book_list/v0/?category_id=507", "script": "genrecontent.js" },
		{ "title": "清朝", "input": "/api/author/library/book_list/v0/?category_id=503", "script": "genrecontent.js" },
		{ "title": "宋朝", "input": "/api/author/library/book_list/v0/?category_id=501", "script": "genrecontent.js" },
		{ "title": "断层", "input": "/api/author/library/book_list/v0/?category_id=500", "script": "genrecontent.js" },
		{ "title": "武将", "input": "/api/author/library/book_list/v0/?category_id=497", "script": "genrecontent.js" },
		{ "title": "国运", "input": "/api/author/library/book_list/v0/?category_id=496", "script": "genrecontent.js" },
		{ "title": "职场商战", "input": "/api/author/library/book_list/v0/?category_id=485", "script": "genrecontent.js" },
		{ "title": "虐恋情深", "input": "/api/author/library/book_list/v0/?category_id=481", "script": "genrecontent.js" },
		{ "title": "日久生情", "input": "/api/author/library/book_list/v0/?category_id=474", "script": "genrecontent.js" },
		{ "title": "豪门世家", "input": "/api/author/library/book_list/v0/?category_id=473", "script": "genrecontent.js" },
		{ "title": "综漫", "input": "/api/author/library/book_list/v0/?category_id=465", "script": "genrecontent.js" },
		{ "title": "异世穿越", "input": "/api/author/library/book_list/v0/?category_id=464", "script": "genrecontent.js" },
		{ "title": "独宠", "input": "/api/author/library/book_list/v0/?category_id=460", "script": "genrecontent.js" },
		{ "title": "开局", "input": "/api/author/library/book_list/v0/?category_id=453", "script": "genrecontent.js" },
		{ "title": "架空", "input": "/api/author/library/book_list/v0/?category_id=452", "script": "genrecontent.js" },
		{ "title": "奇幻仙侠", "input": "/api/author/library/book_list/v0/?category_id=259", "script": "genrecontent.js" },
		{ "title": "都市", "input": "/api/author/library/book_list/v0/?category_id=1", "script": "genrecontent.js" },
		{ "title": "现代言情", "input": "/api/author/library/book_list/v0/?category_id=3", "script": "genrecontent.js" },
		{ "title": "古代言情", "input": "/api/author/library/book_list/v0/?category_id=5", "script": "genrecontent.js" },
		{ "title": "玄幻", "input": "/api/author/library/book_list/v0/?category_id=7", "script": "genrecontent.js" },
		{ "title": "历史", "input": "/api/author/library/book_list/v0/?category_id=12", "script": "genrecontent.js" },
		{ "title": "体育", "input": "/api/author/library/book_list/v0/?category_id=15", "script": "genrecontent.js" },
		{ "title": "武侠", "input": "/api/author/library/book_list/v0/?category_id=16", "script": "genrecontent.js" },
		{ "title": "幻想言情", "input": "/api/author/library/book_list/v0/?category_id=32", "script": "genrecontent.js" },
		{ "title": "总裁", "input": "/api/author/library/book_list/v0/?category_id=29", "script": "genrecontent.js" },
		{ "title": "多女主", "input": "/api/author/library/book_list/v0/?category_id=91", "script": "genrecontent.js" },
		{ "title": "赘婿", "input": "/api/author/library/book_list/v0/?category_id=25", "script": "genrecontent.js" },
		{ "title": "忠犬", "input": "/api/author/library/book_list/v0/?category_id=865", "script": "genrecontent.js" },
		{ "title": "全能", "input": "/api/author/library/book_list/v0/?category_id=856", "script": "genrecontent.js" },
		{ "title": "白切黑", "input": "/api/author/library/book_list/v0/?category_id=853", "script": "genrecontent.js" },
		{ "title": "双学霸", "input": "/api/author/library/book_list/v0/?category_id=849", "script": "genrecontent.js" },
		{ "title": "位尊权重", "input": "/api/author/library/book_list/v0/?category_id=1456", "script": "genrecontent.js" },
		{ "title": "作精", "input": "/api/author/library/book_list/v0/?category_id=521", "script": "genrecontent.js" },
		{ "title": "大佬", "input": "/api/author/library/book_list/v0/?category_id=520", "script": "genrecontent.js" },
		{ "title": "大小姐", "input": "/api/author/library/book_list/v0/?category_id=519", "script": "genrecontent.js" },
		{ "title": "特工", "input": "/api/author/library/book_list/v0/?category_id=518", "script": "genrecontent.js" },
		{ "title": "游戏主播", "input": "/api/author/library/book_list/v0/?category_id=509", "script": "genrecontent.js" },
		{ "title": "神探", "input": "/api/author/library/book_list/v0/?category_id=506", "script": "genrecontent.js" },
		{ "title": "宫廷侯爵", "input": "/api/author/library/book_list/v0/?category_id=502", "script": "genrecontent.js" },
		{ "title": "皇帝", "input": "/api/author/library/book_list/v0/?category_id=498", "script": "genrecontent.js" },
		{ "title": "将军", "input": "/api/author/library/book_list/v0/?category_id=492", "script": "genrecontent.js" },
		{ "title": "毒医", "input": "/api/author/library/book_list/v0/?category_id=491", "script": "genrecontent.js" },
		{ "title": "厨娘", "input": "/api/author/library/book_list/v0/?category_id=490", "script": "genrecontent.js" },
		{ "title": "律师", "input": "/api/author/library/book_list/v0/?category_id=488", "script": "genrecontent.js" },
		{ "title": "医生", "input": "/api/author/library/book_list/v0/?category_id=487", "script": "genrecontent.js" },
		{ "title": "明星", "input": "/api/author/library/book_list/v0/?category_id=486", "script": "genrecontent.js" },
		{ "title": "替身", "input": "/api/author/library/book_list/v0/?category_id=470", "script": "genrecontent.js" },
		{ "title": "双面", "input": "/api/author/library/book_list/v0/?category_id=469", "script": "genrecontent.js" },
		{ "title": "冰山", "input": "/api/author/library/book_list/v0/?category_id=468", "script": "genrecontent.js" },
		{ "title": "古灵精怪", "input": "/api/author/library/book_list/v0/?category_id=459", "script": "genrecontent.js" },
		{ "title": "天作之合", "input": "/api/author/library/book_list/v0/?category_id=455", "script": "genrecontent.js" },
		{ "title": "可盐可甜", "input": "/api/author/library/book_list/v0/?category_id=454", "script": "genrecontent.js" },
		{ "title": "无CP", "input": "/api/author/library/book_list/v0/?category_id=392", "script": "genrecontent.js" },
		{ "title": "单女主", "input": "/api/author/library/book_list/v0/?category_id=389", "script": "genrecontent.js" },
		{ "title": "校花", "input": "/api/author/library/book_list/v0/?category_id=385", "script": "genrecontent.js" },
		{ "title": "无女主", "input": "/api/author/library/book_list/v0/?category_id=391", "script": "genrecontent.js" },
		{ "title": "病娇", "input": "/api/author/library/book_list/v0/?category_id=380", "script": "genrecontent.js" },
		{ "title": "女帝", "input": "/api/author/library/book_list/v0/?category_id=378", "script": "genrecontent.js" },
		{ "title": "特种兵", "input": "/api/author/library/book_list/v0/?category_id=375", "script": "genrecontent.js" },
		{ "title": "反派", "input": "/api/author/library/book_list/v0/?category_id=369", "script": "genrecontent.js" },
		{ "title": "萌宝", "input": "/api/author/library/book_list/v0/?category_id=28", "script": "genrecontent.js" },
		{ "title": "神医", "input": "/api/author/library/book_list/v0/?category_id=26", "script": "genrecontent.js" },
		{ "title": "宠妻", "input": "/api/author/library/book_list/v0/?category_id=30", "script": "genrecontent.js" },
		{ "title": "奶爸", "input": "/api/author/library/book_list/v0/?category_id=42", "script": "genrecontent.js" },
		{ "title": "学霸", "input": "/api/author/library/book_list/v0/?category_id=82", "script": "genrecontent.js" },
		{ "title": "公主", "input": "/api/author/library/book_list/v0/?category_id=83", "script": "genrecontent.js" },
		{ "title": "皇后", "input": "/api/author/library/book_list/v0/?category_id=84", "script": "genrecontent.js" },
		{ "title": "王妃", "input": "/api/author/library/book_list/v0/?category_id=85", "script": "genrecontent.js" },
		{ "title": "女强", "input": "/api/author/library/book_list/v0/?category_id=86", "script": "genrecontent.js" },
		{ "title": "皇叔", "input": "/api/author/library/book_list/v0/?category_id=87", "script": "genrecontent.js" },
		{ "title": "嫡女", "input": "/api/author/library/book_list/v0/?category_id=88", "script": "genrecontent.js" },
		{ "title": "精灵", "input": "/api/author/library/book_list/v0/?category_id=89", "script": "genrecontent.js" },
		{ "title": "天才", "input": "/api/author/library/book_list/v0/?category_id=90", "script": "genrecontent.js" },
		{ "title": "腹黑", "input": "/api/author/library/book_list/v0/?category_id=92", "script": "genrecontent.js" },
		{ "title": "扮猪吃虎", "input": "/api/author/library/book_list/v0/?category_id=93", "script": "genrecontent.js" },
		{ "title": "团宠", "input": "/api/author/library/book_list/v0/?category_id=94", "script": "genrecontent.js" },
		{ "title": "代嫁代娶", "input": "/api/author/library/book_list/v0/?category_id=1458", "script": "genrecontent.js" },
		{ "title": "攻略反派", "input": "/api/author/library/book_list/v0/?category_id=1459", "script": "genrecontent.js" },
		{ "title": "风水秘术", "input": "/api/author/library/book_list/v0/?category_id=1455", "script": "genrecontent.js" },
		{ "title": "斩神衍生", "input": "/api/author/library/book_list/v0/?category_id=1062", "script": "genrecontent.js" },
		{ "title": "十日衍生", "input": "/api/author/library/book_list/v0/?category_id=1060", "script": "genrecontent.js" },
		{ "title": "西游衍生", "input": "/api/author/library/book_list/v0/?category_id=373", "script": "genrecontent.js" },
		{ "title": "公版衍生", "input": "/api/author/library/book_list/v0/?category_id=1037", "script": "genrecontent.js" },
		{ "title": "红楼衍生", "input": "/api/author/library/book_list/v0/?category_id=1036", "script": "genrecontent.js" },
		{ "title": "甄嬛衍生", "input": "/api/author/library/book_list/v0/?category_id=1035", "script": "genrecontent.js" },
		{ "title": "如懿衍生", "input": "/api/author/library/book_list/v0/?category_id=1034", "script": "genrecontent.js" },
		{ "title": "都市江湖", "input": "/api/author/library/book_list/v0/?category_id=1460", "script": "genrecontent.js" },
		{ "title": "男二上位", "input": "/api/author/library/book_list/v0/?category_id=1457", "script": "genrecontent.js" },
		{ "title": "惊悚游戏", "input": "/api/author/library/book_list/v0/?category_id=537", "script": "genrecontent.js" },
		{ "title": "追夫", "input": "/api/author/library/book_list/v0/?category_id=872", "script": "genrecontent.js" },
		{ "title": "卡牌", "input": "/api/author/library/book_list/v0/?category_id=874", "script": "genrecontent.js" },
		{ "title": "山海经", "input": "/api/author/library/book_list/v0/?category_id=875", "script": "genrecontent.js" },
		{ "title": "胎穿", "input": "/api/author/library/book_list/v0/?category_id=876", "script": "genrecontent.js" },
		{ "title": "捉鬼", "input": "/api/author/library/book_list/v0/?category_id=867", "script": "genrecontent.js" },
		{ "title": "剑修", "input": "/api/author/library/book_list/v0/?category_id=868", "script": "genrecontent.js" },
		{ "title": "废土", "input": "/api/author/library/book_list/v0/?category_id=869", "script": "genrecontent.js" },
		{ "title": "相互救赎", "input": "/api/author/library/book_list/v0/?category_id=860", "script": "genrecontent.js" },
		{ "title": "宠夫", "input": "/api/author/library/book_list/v0/?category_id=861", "script": "genrecontent.js" },
		{ "title": "副本", "input": "/api/author/library/book_list/v0/?category_id=864", "script": "genrecontent.js" },
		{ "title": "黑科技", "input": "/api/author/library/book_list/v0/?category_id=854", "script": "genrecontent.js" },
		{ "title": "无脑爽", "input": "/api/author/library/book_list/v0/?category_id=850", "script": "genrecontent.js" },
		{ "title": "魂穿", "input": "/api/author/library/book_list/v0/?category_id=852", "script": "genrecontent.js" },
		{ "title": "高手下山", "input": "/api/author/library/book_list/v0/?category_id=845", "script": "genrecontent.js" },
		{ "title": "黑化", "input": "/api/author/library/book_list/v0/?category_id=846", "script": "genrecontent.js" },
		{ "title": "养崽", "input": "/api/author/library/book_list/v0/?category_id=847", "script": "genrecontent.js" },
		{ "title": "年龄差", "input": "/api/author/library/book_list/v0/?category_id=848", "script": "genrecontent.js" },
		{ "title": "迪化", "input": "/api/author/library/book_list/v0/?category_id=843", "script": "genrecontent.js" },
		{ "title": "真假千金", "input": "/api/author/library/book_list/v0/?category_id=844", "script": "genrecontent.js" },
		{ "title": "久别重逢", "input": "/api/author/library/book_list/v0/?category_id=839", "script": "genrecontent.js" },
		{ "title": "发家致富", "input": "/api/author/library/book_list/v0/?category_id=840", "script": "genrecontent.js" },
		{ "title": "无后宫", "input": "/api/author/library/book_list/v0/?category_id=838", "script": "genrecontent.js" },
		{ "title": "养成", "input": "/api/author/library/book_list/v0/?category_id=835", "script": "genrecontent.js" },
		{ "title": "互宠", "input": "/api/author/library/book_list/v0/?category_id=836", "script": "genrecontent.js" },
		{ "title": "争霸", "input": "/api/author/library/book_list/v0/?category_id=837", "script": "genrecontent.js" },
		{ "title": "1v1", "input": "/api/author/library/book_list/v0/?category_id=834", "script": "genrecontent.js" },
		{ "title": "升级流", "input": "/api/author/library/book_list/v0/?category_id=830", "script": "genrecontent.js" },
		{ "title": "灵魂互换", "input": "/api/author/library/book_list/v0/?category_id=831", "script": "genrecontent.js" },
		{ "title": "科举", "input": "/api/author/library/book_list/v0/?category_id=832", "script": "genrecontent.js" },
		{ "title": "年下", "input": "/api/author/library/book_list/v0/?category_id=829", "script": "genrecontent.js" },
		{ "title": "婚恋", "input": "/api/author/library/book_list/v0/?category_id=34", "script": "genrecontent.js" },
		{ "title": "封神", "input": "/api/author/library/book_list/v0/?category_id=731", "script": "genrecontent.js" },
		{ "title": "四合院", "input": "/api/author/library/book_list/v0/?category_id=495", "script": "genrecontent.js" },
		{ "title": "电竞", "input": "/api/author/library/book_list/v0/?category_id=508", "script": "genrecontent.js" },
		{ "title": "双重生", "input": "/api/author/library/book_list/v0/?category_id=524", "script": "genrecontent.js" },
		{ "title": "前世今生", "input": "/api/author/library/book_list/v0/?category_id=523", "script": "genrecontent.js" },
		{ "title": "双洁", "input": "/api/author/library/book_list/v0/?category_id=702", "script": "genrecontent.js" },
		{ "title": "追妻火葬场", "input": "/api/author/library/book_list/v0/?category_id=616", "script": "genrecontent.js" },
		{ "title": "乡村", "input": "/api/author/library/book_list/v0/?category_id=11", "script": "genrecontent.js" },
		{ "title": "逃荒", "input": "/api/author/library/book_list/v0/?category_id=557", "script": "genrecontent.js" },
		{ "title": "同人", "input": "/api/author/library/book_list/v0/?category_id=538", "script": "genrecontent.js" },
		{ "title": "打脸", "input": "/api/author/library/book_list/v0/?category_id=522", "script": "genrecontent.js" },
		{ "title": "破案", "input": "/api/author/library/book_list/v0/?category_id=505", "script": "genrecontent.js" },
		{ "title": "囤物资", "input": "/api/author/library/book_list/v0/?category_id=494", "script": "genrecontent.js" },
		{ "title": "钓鱼", "input": "/api/author/library/book_list/v0/?category_id=493", "script": "genrecontent.js" },
		{ "title": "HE", "input": "/api/author/library/book_list/v0/?category_id=484", "script": "genrecontent.js" },
		{ "title": "相爱相杀", "input": "/api/author/library/book_list/v0/?category_id=483", "script": "genrecontent.js" },
		{ "title": "暗恋", "input": "/api/author/library/book_list/v0/?category_id=482", "script": "genrecontent.js" },
		{ "title": "逃婚", "input": "/api/author/library/book_list/v0/?category_id=480", "script": "genrecontent.js" },
		{ "title": "带球跑", "input": "/api/author/library/book_list/v0/?category_id=479", "script": "genrecontent.js" },
		{ "title": "强强", "input": "/api/author/library/book_list/v0/?category_id=478", "script": "genrecontent.js" },
		{ "title": "一见钟情", "input": "/api/author/library/book_list/v0/?category_id=477", "script": "genrecontent.js" },
		{ "title": "双向奔赴", "input": "/api/author/library/book_list/v0/?category_id=476", "script": "genrecontent.js" },
		{ "title": "破镜重圆", "input": "/api/author/library/book_list/v0/?category_id=475", "script": "genrecontent.js" },
		{ "title": "契约婚姻", "input": "/api/author/library/book_list/v0/?category_id=471", "script": "genrecontent.js" },
		{ "title": "隐婚", "input": "/api/author/library/book_list/v0/?category_id=467", "script": "genrecontent.js" },
		{ "title": "闪婚", "input": "/api/author/library/book_list/v0/?category_id=466", "script": "genrecontent.js" },
		{ "title": "今穿古", "input": "/api/author/library/book_list/v0/?category_id=463", "script": "genrecontent.js" },
		{ "title": "古穿今", "input": "/api/author/library/book_list/v0/?category_id=462", "script": "genrecontent.js" },
		{ "title": "群穿", "input": "/api/author/library/book_list/v0/?category_id=461", "script": "genrecontent.js" },
		{ "title": "护短", "input": "/api/author/library/book_list/v0/?category_id=458", "script": "genrecontent.js" },
		{ "title": "虐渣", "input": "/api/author/library/book_list/v0/?category_id=457", "script": "genrecontent.js" },
		{ "title": "情有独钟", "input": "/api/author/library/book_list/v0/?category_id=456", "script": "genrecontent.js" },
		{ "title": "马甲", "input": "/api/author/library/book_list/v0/?category_id=266", "script": "genrecontent.js" },
		{ "title": "先婚后爱", "input": "/api/author/library/book_list/v0/?category_id=265", "script": "genrecontent.js" },
		{ "title": "医术", "input": "/api/author/library/book_list/v0/?category_id=247", "script": "genrecontent.js" },
		{ "title": "网游", "input": "/api/author/library/book_list/v0/?category_id=372", "script": "genrecontent.js" },
		{ "title": "奥特同人", "input": "/api/author/library/book_list/v0/?category_id=367", "script": "genrecontent.js" },
		{ "title": "求生", "input": "/api/author/library/book_list/v0/?category_id=379", "script": "genrecontent.js" },
		{ "title": "女扮男装", "input": "/api/author/library/book_list/v0/?category_id=388", "script": "genrecontent.js" },
		{ "title": "青梅竹马", "input": "/api/author/library/book_list/v0/?category_id=387", "script": "genrecontent.js" },
		{ "title": "无敌", "input": "/api/author/library/book_list/v0/?category_id=384", "script": "genrecontent.js" },
		{ "title": "民国", "input": "/api/author/library/book_list/v0/?category_id=390", "script": "genrecontent.js" },
		{ "title": "九叔", "input": "/api/author/library/book_list/v0/?category_id=383", "script": "genrecontent.js" },
		{ "title": "穿书", "input": "/api/author/library/book_list/v0/?category_id=382", "script": "genrecontent.js" },
		{ "title": "聊天群", "input": "/api/author/library/book_list/v0/?category_id=381", "script": "genrecontent.js" },
		{ "title": "大秦", "input": "/api/author/library/book_list/v0/?category_id=377", "script": "genrecontent.js" },
		{ "title": "龙珠", "input": "/api/author/library/book_list/v0/?category_id=376", "script": "genrecontent.js" },
		{ "title": "漫威", "input": "/api/author/library/book_list/v0/?category_id=374", "script": "genrecontent.js" },
		{ "title": "神奇宝贝", "input": "/api/author/library/book_list/v0/?category_id=371", "script": "genrecontent.js" },
		{ "title": "海贼", "input": "/api/author/library/book_list/v0/?category_id=370", "script": "genrecontent.js" },
		{ "title": "火影", "input": "/api/author/library/book_list/v0/?category_id=368", "script": "genrecontent.js" },
		{ "title": "职场", "input": "/api/author/library/book_list/v0/?category_id=127", "script": "genrecontent.js" },
		{ "title": "明朝", "input": "/api/author/library/book_list/v0/?category_id=126", "script": "genrecontent.js" },
		{ "title": "家庭", "input": "/api/author/library/book_list/v0/?category_id=125", "script": "genrecontent.js" },
		{ "title": "三国", "input": "/api/author/library/book_list/v0/?category_id=67", "script": "genrecontent.js" },
		{ "title": "末世", "input": "/api/author/library/book_list/v0/?category_id=68", "script": "genrecontent.js" },
		{ "title": "直播", "input": "/api/author/library/book_list/v0/?category_id=69", "script": "genrecontent.js" },
		{ "title": "无限流", "input": "/api/author/library/book_list/v0/?category_id=70", "script": "genrecontent.js" },
		{ "title": "诸天万界", "input": "/api/author/library/book_list/v0/?category_id=71", "script": "genrecontent.js" },
		{ "title": "兽世", "input": "/api/author/library/book_list/v0/?category_id=72", "script": "genrecontent.js" },
		{ "title": "大唐", "input": "/api/author/library/book_list/v0/?category_id=73", "script": "genrecontent.js" },
		{ "title": "宠物", "input": "/api/author/library/book_list/v0/?category_id=74", "script": "genrecontent.js" },
		{ "title": "外卖", "input": "/api/author/library/book_list/v0/?category_id=75", "script": "genrecontent.js" },
		{ "title": "清穿", "input": "/api/author/library/book_list/v0/?category_id=76", "script": "genrecontent.js" },
		{ "title": "星际", "input": "/api/author/library/book_list/v0/?category_id=77", "script": "genrecontent.js" },
		{ "title": "美食", "input": "/api/author/library/book_list/v0/?category_id=78", "script": "genrecontent.js" },
		{ "title": "剑道", "input": "/api/author/library/book_list/v0/?category_id=80", "script": "genrecontent.js" },
		{ "title": "盗墓", "input": "/api/author/library/book_list/v0/?category_id=81", "script": "genrecontent.js" },
		{ "title": "虐文", "input": "/api/author/library/book_list/v0/?category_id=95", "script": "genrecontent.js" },
		{ "title": "甜宠", "input": "/api/author/library/book_list/v0/?category_id=96", "script": "genrecontent.js" },
		{ "title": "灵异", "input": "/api/author/library/book_list/v0/?category_id=100", "script": "genrecontent.js" },
		{ "title": "校园", "input": "/api/author/library/book_list/v0/?category_id=4", "script": "genrecontent.js" },
		{ "title": "鉴宝", "input": "/api/author/library/book_list/v0/?category_id=17", "script": "genrecontent.js" },
		{ "title": "系统", "input": "/api/author/library/book_list/v0/?category_id=19", "script": "genrecontent.js" },
		{ "title": "神豪", "input": "/api/author/library/book_list/v0/?category_id=20", "script": "genrecontent.js" },
		{ "title": "重生", "input": "/api/author/library/book_list/v0/?category_id=36", "script": "genrecontent.js" },
		{ "title": "穿越", "input": "/api/author/library/book_list/v0/?category_id=37", "script": "genrecontent.js" },
		{ "title": "二次元", "input": "/api/author/library/book_list/v0/?category_id=39", "script": "genrecontent.js" },
		{ "title": "海岛", "input": "/api/author/library/book_list/v0/?category_id=40", "script": "genrecontent.js" },
		{ "title": "娱乐圈", "input": "/api/author/library/book_list/v0/?category_id=43", "script": "genrecontent.js" },
		{ "title": "空间", "input": "/api/author/library/book_list/v0/?category_id=44", "script": "genrecontent.js" },
		{ "title": "推理", "input": "/api/author/library/book_list/v0/?category_id=61", "script": "genrecontent.js" },
		{ "title": "洪荒", "input": "/api/author/library/book_list/v0/?category_id=66", "script": "genrecontent.js" }
	]);
}
