function execute() {
    return Response.success([
        { title: "不限人气", input: "/ajax_novels/monthvisit_0_0_{0}.htm", script: "gen.js" },
        { title: "连载人气", input: "/ajax_novels/monthvisit_0_2_{0}.htm", script: "gen.js" },
        { title: "全本人气", input: "/ajax_novels/monthvisit_0_1_{0}.htm", script: "gen.js" },
        { title: "不限推荐", input: "/ajax_novels/allvote_0_0_{0}.htm", script: "gen.js" },
        { title: "连载推荐", input: "/ajax_novels/allvote_0_2_{0}.htm", script: "gen.js" },
        { title: "全本推荐", input: "/ajax_novels/allvote_0_1_{0}.htm", script: "gen.js" },

        {title: "诸天流 - New", input: "chư thiên&new", script: "search.js"},
        {title: "诸天流 - Update", input: "chư thiên&update", script: "search.js"},
        {title: "诸天流 - View", input: "chư thiên&view", script: "search.js"},
        {title: "诸天流 - Week", input: "chư thiên&viewweek", script: "search.js"},
        {title: "诸天流 - Day", input: "chư thiên&viewday", script: "search.js"},
        {title: "诸天流 - Like", input: "chư thiên&like", script: "search.js"},
        {title: "诸天流 - Follow", input: "chư thiên&following", script: "search.js"},
        {title: "诸天流 - Bookmark", input: "chư thiên&bookmarked", script: "search.js"},
        
        {title: "官场 - Update", input: "quantruongcholamviec,", script: "tag.js"},
        {title: "官场 - New", input: "quantruongcholamviec,&new", script: "tag.js"},
        {title: "官场 - View", input: "quantruongcholamviec,&view", script: "tag.js"},
        {title: "官场 - Week", input: "quantruongcholamviec,&viewweek", script: "tag.js"},
        {title: "官场 - Day", input: "quantruongcholamviec,&viewday", script: "tag.js"},
        {title: "官场 - Bookmark", input: "quantruongcholamviec,&bookmarked", script: "tag.js"},

        {title: "武侠 - Update", input: "vuhiep,", script: "tag.js"},
        {title: "武侠 - New", input: "vuhiep,&new", script: "tag.js"},
        {title: "武侠 - View", input: "vuhiep,&view", script: "tag.js"},
        {title: "武侠 - Week", input: "vuhiep,&viewweek", script: "tag.js"},
        {title: "武侠 - Day", input: "vuhiep,&viewday", script: "tag.js"},
        {title: "武侠 - Bookmark", input: "vuhiep,&bookmarked", script: "tag.js"},

        {title: "时空 - Update", input: "xuyenquathoikhong,", script: "tag.js"},
        {title: "时空 - New", input: "xuyenquathoikhong,&new", script: "tag.js"},
        {title: "时空 - View", input: "xuyenquathoikhong,&view", script: "tag.js"},
        {title: "时空 - Week", input: "xuyenquathoikhong,&viewweek", script: "tag.js"},
        {title: "时空 - Day", input: "xuyenquathoikhong,&viewday", script: "tag.js"},
        {title: "时空 - Bookmark", input: "xuyenquathoikhong,&bookmarked", script: "tag.js"},

        {title: "同人 - Update", input: "dongnhan,", script: "tag.js"},
        {title: "同人 - New", input: "dongnhan,&new", script: "tag.js"},
        {title: "同人 - View", input: "dongnhan,&view", script: "tag.js"},
        {title: "同人 - Week", input: "dongnhan,&viewweek", script: "tag.js"},
        {title: "同人 - Day", input: "dongnhan,&viewday", script: "tag.js"},
        {title: "同人 - Bookmark", input: "dongnhan,&bookmarked", script: "tag.js"},
        
        {title: "玄幻魔法 - Update", input: "huyenhuyenmaphap,", script: "tag.js"},
        {title: "玄幻魔法 - New", input: "huyenhuyenmaphap,&new", script: "tag.js"},
        {title: "玄幻魔法 - View", input: "huyenhuyenmaphap,&view", script: "tag.js"},
        {title: "玄幻魔法 - Week", input: "huyenhuyenmaphap,&viewweek", script: "tag.js"},
        {title: "玄幻魔法 - Day", input: "huyenhuyenmaphap,&viewday", script: "tag.js"},
        {title: "玄幻魔法 - Bookmark", input: "huyenhuyenmaphap,&bookmarked", script: "tag.js"},
        
        {title: "科幻空间 - Update", input: "khoahuyenkhonggian,", script: "tag.js"},
        {title: "科幻空间 - New", input: "khoahuyenkhonggian,&new", script: "tag.js"},
        {title: "科幻空间 - View", input: "khoahuyenkhonggian,&view", script: "tag.js"},
        {title: "科幻空间 - Week", input: "khoahuyenkhonggian,&viewweek", script: "tag.js"},
        {title: "科幻空间 - Day", input: "khoahuyenkhonggian,&viewday", script: "tag.js"},
        {title: "科幻空间 - Bookmark", input: "khoahuyenkhonggian,&bookmarked", script: "tag.js"},

        {title: "聊天群 - New", input: "chat group&new", script: "search.js"},
        {title: "聊天群 - Update", input: "chat group&update", script: "search.js"},
        {title: "聊天群 - View", input: "chat group&view", script: "search.js"},
        {title: "聊天群 - Week", input: "chat group&viewweek", script: "search.js"},
        {title: "聊天群 - Day", input: "chat group&viewday", script: "search.js"},
        {title: "聊天群 - Like", input: "chat group&like", script: "search.js"},
        {title: "聊天群 - Follow", input: "chat group&following", script: "search.js"},
        {title: "聊天群 - Bookmark", input: "chat group&bookmarked", script: "search.js"},

        { title: "New", input: "&new", script: "search.js" },
        { title: "Update", input: "&update", script: "search.js" },
        { title: "View Week", input: "&viewweek", script: "search.js" },
        { title: "View Day", input: "&viewday", script: "search.js" },
        { title: "View", input: "&view", script: "search.js" },
        { title: "Like", input: "&like", script: "search.js" },
        { title: "Follow", input: "&following", script: "search.js" },
        { title: "Bookmark", input: "&bookmarked", script: "search.js" },
        
        { title: "思路清奇", input: "/思路清奇/{0}/", script: "gen2.js" },
        { title: "穿越", input: "/穿越/{0}/", script: "gen2.js" },
        { title: "轻松", input: "/轻松/{0}/", script: "gen2.js" },
        { title: "系统流", input: "/系统流/{0}/", script: "gen2.js" },
        { title: "重生", input: "/重生/{0}/", script: "gen2.js" },
        { title: "爽文", input: "/爽文/{0}/", script: "gen2.js" },
        { title: "无敌流", input: "/无敌流/{0}/", script: "gen2.js" },
        { title: "种田", input: "/种田/{0}/", script: "gen2.js" },
        { title: "逆袭", input: "/逆袭/{0}/", script: "gen2.js" },
        { title: "经营", input: "/经营/{0}/", script: "gen2.js" },
        { title: "杀伐果断", input: "/杀伐果断/{0}/", script: "gen2.js" },
        { title: "快节奏", input: "/快节奏/{0}/", script: "gen2.js" },
        { title: "日常文", input: "/日常文/{0}/", script: "gen2.js" },
        { title: "架空", input: "/架空/{0}/", script: "gen2.js" },
        { title: "打脸", input: "/打脸/{0}/", script: "gen2.js" },
        { title: "萌宝", input: "/萌宝/{0}/", script: "gen2.js" },
        { title: "校园", input: "/校园/{0}/", script: "gen2.js" },
        { title: "无限流", input: "/无限流/{0}/", script: "gen2.js" },
        { title: "智商在线", input: "/智商在线/{0}/", script: "gen2.js" },
        { title: "冷静", input: "/冷静/{0}/", script: "gen2.js" },
        { title: "空间", input: "/空间/{0}/", script: "gen2.js" },
        { title: "异能", input: "/异能/{0}/", script: "gen2.js" },
        { title: "诸天流", input: "/诸天流/{0}/", script: "gen2.js" },
        { title: "快穿", input: "/快穿/{0}/", script: "gen2.js" },
        { title: "脑洞大", input: "/脑洞大/{0}/", script: "gen2.js" },
        { title: "金手指", input: "/金手指/{0}/", script: "gen2.js" },
        { title: "穿书", input: "/穿书/{0}/", script: "gen2.js" },
        { title: "大佬", input: "/大佬/{0}/", script: "gen2.js" },
        { title: "文娱", input: "/文娱/{0}/", script: "gen2.js" },
        { title: "娱乐圈", input: "/娱乐圈/{0}/", script: "gen2.js" },
        { title: "赚钱", input: "/赚钱/{0}/", script: "gen2.js" },
        { title: "强者归来", input: "/强者归来/{0}/", script: "gen2.js" },
    ]);
}
