function execute() {
    return Response.success([
        { title: "不限人气", input: "/ajax_novels/monthvisit_0_0_{0}.htm", script: "gen.js" },
        { title: "连载人气", input: "/ajax_novels/monthvisit_0_2_{0}.htm", script: "gen.js" },
        { title: "全本人气", input: "/ajax_novels/monthvisit_0_1_{0}.htm", script: "gen.js" },
        { title: "不限推荐", input: "/ajax_novels/allvote_0_0_{0}.htm", script: "gen.js" },
        { title: "连载推荐", input: "/ajax_novels/allvote_0_2_{0}.htm", script: "gen.js" },
        { title: "全本推荐", input: "/ajax_novels/allvote_0_1_{0}.htm", script: "gen.js" },
        
        { title: "思路清奇", input: "/思路清奇/{0}/", script: "gen2.js" },
        { title: "穿越", input: "/穿越/{0}/", script: "gen2.js" },
        { title: "轻松", input: "/轻松/{0}/", script: "gen2.js" },
        { title: "系统流", input: "/系统流/{0}/", script: "gen2.js" },
        { title: "重生", input: "/重生/{0}/", script: "gen2.js" },
        { title: "爽文", input: "/爽文/{0}/", script: "gen2.js" },
        { title: "无敌流", input: "/无敌流/{0}/", script: "gen2.js" },
        { title: "种田", input: "/种田/{0}/", script: "gen2.js" },
        { title: "逆袭", input: "/逆袭/{0}/", script: "gen2.js" },
        { title: "经营", input: "/经营/{0}/", script: "gen2.js" },
        { title: "杀伐果断", input: "/杀伐果断/{0}/", script: "gen2.js" },
        { title: "快节奏", input: "/快节奏/{0}/", script: "gen2.js" },
        { title: "日常文", input: "/日常文/{0}/", script: "gen2.js" },
        { title: "架空", input: "/架空/{0}/", script: "gen2.js" },
        { title: "打脸", input: "/打脸/{0}/", script: "gen2.js" },
        { title: "萌宝", input: "/萌宝/{0}/", script: "gen2.js" },
        { title: "校园", input: "/校园/{0}/", script: "gen2.js" },
        { title: "无限流", input: "/无限流/{0}/", script: "gen2.js" },
        { title: "智商在线", input: "/智商在线/{0}/", script: "gen2.js" },
        { title: "冷静", input: "/冷静/{0}/", script: "gen2.js" },
        { title: "空间", input: "/空间/{0}/", script: "gen2.js" },
        { title: "异能", input: "/异能/{0}/", script: "gen2.js" },
        { title: "诸天流", input: "/诸天流/{0}/", script: "gen2.js" },
        { title: "快穿", input: "/快穿/{0}/", script: "gen2.js" },
        { title: "脑洞大", input: "/脑洞大/{0}/", script: "gen2.js" },
        { title: "金手指", input: "/金手指/{0}/", script: "gen2.js" },
        { title: "穿书", input: "/穿书/{0}/", script: "gen2.js" },
        { title: "大佬", input: "/大佬/{0}/", script: "gen2.js" },
        { title: "文娱", input: "/文娱/{0}/", script: "gen2.js" },
        { title: "娱乐圈", input: "/娱乐圈/{0}/", script: "gen2.js" },
        { title: "赚钱", input: "/赚钱/{0}/", script: "gen2.js" },
        { title: "强者归来", input: "/强者归来/{0}/", script: "gen2.js" },
    ]);
}
