function execute() {
    return Response.success([
        { title: "诸天", input: "诸天", script: "search.js" },
        { title: "聊天群", input: "聊天群", script: "search.js" },
        { title: "万界", input: "万界", script: "search.js" },
        { title: "无限", input: "无限", script: "search.js" },

        { title: "吞噬", input: "吞噬", script: "search.js" },
        { title: "凡人", input: "凡人", script: "search.js" },
        { title: "完美世界", input: "完美世界", script: "search.js" },
        { title: "遮天", input: "遮天", script: "search.js" },
        { title: "神墓", input: "神墓", script: "search.js" },
        { title: "圣墟", input: "圣墟", script: "search.js" },
        { title: "龙珠", input: "龙珠", script: "search.js" },
        { title: "火影", input: "火影", script: "search.js" },
        { title: "木叶", input: "火影", script: "search.js" },
        { title: "鸣人", input: "鸣人", script: "search.js" },
        { title: "犬夜叉", input: "犬夜叉", script: "search.js" },
        { title: "海贼", input: "海贼", script: "search.js" },
        { title: "妖尾", input: "妖尾", script: "search.js" },
        { title: "假面骑士", input: "假面骑士", script: "search.js" },
        { title: "骑士", input: "骑士", script: "search.js" },
        { title: "奥特曼", input: "奥特曼", script: "search.js" },
        { title: "死神", input: "死神", script: "search.js" },
        { title: "一世之尊", input: "一世之尊", script: "search.js" },
        { title: "西游", input: "西游", script: "search.js" },
        { title: "大奉", input: "大奉", script: "search.js" },
        { title: "轮回", input: "轮回", script: "search.js" },
        { title: "庆余年", input: "庆余年", script: "search.js" },
        { title: "斗罗", input: "斗罗", script: "search.js" },
        { title: "妖神记", input: "妖神记", script: "search.js" },
        { title: "师兄啊", input: "师兄啊", script: "search.js" },
        { title: "全職獵人", input: "全職獵人", script: "search.js" },
        { title: "全職法師", input: "全職法師", script: "search.js" },
        { title: "剑来", input: "剑来", script: "search.js" },
        { title: "雪中", input: "雪中", script: "search.js" },
        
        { title: "動漫同人", input: "https://uukanshu.cc/class_9_{0}.html", script: "gen.js" },
        { title: "玄幻奇幻", input: "https://uukanshu.cc/class_1_{0}.html", script: "gen.js" },
        { title: "武俠仙俠", input: "https://uukanshu.cc/class_2_{0}.html", script: "gen.js" },
        { title: "武俠仙俠", input: "https://uukanshu.cc/class_3_{0}.html", script: "gen.js" },
        { title: "妖怪茶話會", input: "https://uukanshu.cc/class_5_{0}.html", script: "gen.js" },
        { title: "歷史軍事", input: "https://uukanshu.cc/class_4_{0}.html", script: "gen.js" },
        { title: "遊戲競技", input: "https://uukanshu.cc/class_6_{0}.html", script: "gen.js" },
        { title: "恐怖靈異", input: "https://uukanshu.cc/class_7_{0}.html", script: "gen.js" },
        { title: "其他類型", input: "https://uukanshu.cc/class_10_{0}.html", script: "gen.js" },

        { title: "Update", input: "https://uukanshu.cc/top/lastupdate_{0}.html", script: "gen.js" },
        { title: "New", input: "https://uukanshu.cc/top/postdate_{0}.html", script: "gen.js" },
        { title: "View tuần", input: "https://uukanshu.cc/top/weekvisit_{0}.html", script: "gen.js" },
        { title: "View tháng", input: "https://uukanshu.cc/top/monthvisit_{0}.html", script: "gen.js" },
        { title: "View", input: "https://uukanshu.cc/top/allvisit_{0}.html", script: "gen.js" },
        { title: "Vote tuần", input: "https://uukanshu.cc/top/weekvote_{0}.html", script: "gen.js" },
        { title: "Vote tháng", input: "https://uukanshu.cc/top/monthvote_{0}.html", script: "gen.js" },
        { title: "Vote", input: "https://uukanshu.cc/top/allvote_{0}.html", script: "gen.js" },
        { title: "Rating", input: "https://uukanshu.cc/top/goodnum_{0}.html", script: "gen.js" },
        { title: "Done", input: "https://uukanshu.cc/quanben/{0}.html", script: "gen.js" },
    ]);
}